### ISSUE TITLE
Add all-contributors to the repo

### ISSUE THREAD

**Issue by siddharthkp** [siddharthkp/bundlesize#100]
@kentcdodds  made the coolest thing ever: [all-contributors](https://github.com/kentcdodds/all-contributors)

- Add it the readme
- Add it to CONTRIBUTING.md

**Comment by cg-cnu** [comment]
Can i start with this one ?

**Comment by siddharthkp** [comment]
Yep totally!

**Comment by cg-cnu** [comment]
Setup all-crontributors as dev-dependency. 
Started with the initial list from [here](https://github.com/siddharthkp/bundlesize/graphs/contributors) With contribution as code. 
Whom else should I add. @siddharthkp Any list you have ?

**Comment by siddharthkp** [comment]
This is a good start. You can let people add themselves after that 😄
