### ISSUE TITLE
Add prettier as a precommit hook

### ISSUE THREAD

**Issue by siddharthkp** [siddharthkp/bundlesize#103]
Now that we have multiple collaborators on the repo, it will be useful to add a prettier pre-commit hook to maintain consistency.

This is how you can setup a pre-commit hook: https://www.npmjs.com/package/prettier#pre-commit-hook

My favorite config is: `prettier --write --single-quote --no-semi`, but I'm open to whatever the majority feels comfortable with 😄 

Thanks to @okonet for [lint-staged](https://github.com/okonet/lint-staged) and @typicode for [husky](https://github.com/typicode/husky)!

**Comment by hawkins** [comment]
I'd be happy to knock this one out

**Comment by siddharthkp** [comment]
All yours 😄

**Comment by hawkins** [comment]
Sent in a PR which I think meets your original objectives at #105  👍
