### ISSUE TITLE
How do you keep package-lock.json updated?

### ISSUE THREAD

**Issue by siddharthkp** [siddharthkp/bundlesize#106]
This project uses npm5's `package-lock.json`, I realised that a lot of folks use yarn or an older version of npm.

What this means is that you might not get the same dependencies on your machines.
Moreover, dependencies you add on npm4 will not get added to `package-lock`, this might lead to problems in CI which uses npm5 and will only install packages from package-lock (If I understand correctly, I might be wrong)

How do we get around this problem?

**Comment by SaraVieira** [comment]
I like artem"s idea on react styleguidist :
https://github.com/styleguidist/react-styleguidist/blob/master/dangerfile.js

How do you feel about this?

**Comment by siddharthkp** [comment]
Looks good! Can we just add this as a test?

I haven't used danger before, so I'm not sure how that works 🙈

**Comment by SaraVieira** [comment]
I'll try and make a PR tomorrow ☺️

**Comment by scttcper** [comment]
Can add npm engines to package.json which I think throws a warning if under the version.
https://docs.npmjs.com/files/package.json#engines

**Comment by siddharthkp** [comment]
Great idea! Do you want to help out with that?

**Comment by tohjustin** [comment]
Hi @siddharthkp, I think @SaraVieira could include the change to add `npm engines` to `package.json`. Otherwise I'm glad to create a mini-PR for this =)

**Comment by SaraVieira** [comment]
Hi @tohjustin! 

I'll do that today ☺️
