### ISSUE TITLE
Update readme for todo list

### ISSUE THREAD

**Issue by palashmon** [siddharthkp/bundlesize#109]
Found that readme [**todo**](https://github.com/siddharthkp/bundlesize#todo) section mention about 
> work with other CI tools (**circle**, appveyor, etc.)

But, Circle CI is already working with this package, as mentioned:
> Currently works for Travis CI, **CircleCI**, Wercker, and Drone.

So, please update the **todo** list, as found necessary for this repo.

Regards!

**Comment by siddharthkp** [comment]
Haha, good catch!

Would you like to help out with it?

**Comment by palashmon** [comment]
Sure, I will create a PR for this in a moment. 
Can I assign this issue to me in some way?

**Comment by ThisIzKp** [comment]
@palashmon assigned it to you and added label `work in progress`

**Comment by palashmon** [comment]
Thanks @ThisIzKp. Will create a PR soon.

**Comment by siddharthkp** [comment]
Added you as a collaborator as well!

**Comment by palashmon** [comment]
Thanks so much @siddharthkp
