### ISSUE TITLE
[Discussion] Updating CONTRIBUTING.md

### ISSUE THREAD

**Issue by palashmon** [siddharthkp/bundlesize#111]
**Note:** _This is not a issue actually but more of a open discussion regarding a contributing workflow._

I have been doing some Rnd on [Fork-and-Branch Git Workflow](https://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/) and also on other sites and found that the basic workflow for adding a new feature to a forked repo is like:-

- Fork a GitHub repository. [Same as in our CONTRIBUTING.md :heavy_check_mark: ]
- Clone the forked repository to your local system. :heavy_check_mark: 
- Create a feature branch in which to place your changes. :x:
- Make your changes to the new branch. [Currently done on master :heavy_check_mark: ]
- Commit the changes to the branch. [Currently done on master :heavy_check_mark: ]
- Push the branch to GitHub. :heavy_check_mark:
- Open a pull request from the new branch to the original repo. :heavy_check_mark:

So, do you think it is a best practice to always make the new feature or experimental changes on a new branch? Should we update our `CONTRIBUTING.md` to reflect that too?

Regards!

**Comment by siddharthkp** [comment]
I honestly don't know /shrug 

What's the added benefit that you get with that?

**Comment by palashmon** [comment]
A simple scenario is like:

- User A fork a repo.
- makes changes to master for feature one.
- changes got merged to original repo.
- User A makes changes again to master for feature 2 & 3.
- Feature 2 was declined, but feature 3 was added
- In between multiple users have also made changes to their forked repo.
- Those changes also got merged to original repo.

Now when user A tries to add a new feature 4 to his forked repo master, he gets error because his master is not in sync with original repo master. Also, his master branch has feature 1, 2, 3 & 4, but original repo has only 1 and 3 and changes by other user.

Now, only way for his to fix this is to I guess delete is repo and again fork the original repo.

But, if the user A had created multiple branches for multiple feature, he has to not to worry about this at all, as he can update his forked master [anytime](https://help.github.com/articles/syncing-a-fork/), which never has conflicts with original repo master.

I have faced similar issues at start, so I know this can happen for the first time contributors point of view.

I hope this make sense.

**Comment by nitin42** [comment]
I don't think so `CONTRIBUTING.md` requires an update. But if you still want to continue, I'd recommend dividing it into three sections - 

* Understanding the codebase
* Setting up the environment
* Submitting pull requests
* Testing the changes locally (when the tests will be added)

**Comment by siddharthkp** [comment]
@palashmon Ooh that makes so much sense! I've deleted and forks again in the past 😅

Hi @SaraVieira 😁

I think this is an useful addition 

@nitin42, good idea! splitting into multiple sections would be super useful too!

**Comment by sreetamdas** [comment]
+1, the example @palashmon gave makes sense, and frankly, seems like something that people might overlook easily.
