### ISSUE TITLE
Add Eslint to repo

### ISSUE THREAD

**Issue by SaraVieira** [siddharthkp/bundlesize#116]
Since we are using prettier for the precommit hook I think we should add eslint aswell.

I was thinking of adding:

  * [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb)
  * [eslint-config-prettier](https://www.npmjs.com/package/eslint-config-prettier)
  * [eslint-plugin-compat](https://www.npmjs.com/package/eslint-plugin-compat)
  * [eslint-plugin-import](https://www.npmjs.com/package/eslint-plugin-import)
  * [eslint-plugin-prettier](https://www.npmjs.com/package/eslint-plugin-prettier)

How does that sound ?

**Comment by nitin42** [comment]
Yup! we can use a popular style guide 👍

**Comment by kakadiadarpan** [comment]
How about airbnb?

**Comment by reznord** [comment]
IMO, adding `airbnb` is more than enough. Adding those many plugins just increase the installation time :P

**Comment by palashmon** [comment]
My vote also goes with airbnb :+1:

**Comment by siddharthkp** [comment]
Happy with whatever you guys decide (as long as it can automated on pre-commit) 😄 

_____

I have a slightly different (new formed) opinion on linting:

_⚠️ Warning: grumpiness ahead_

A person working on code should not have to worry about styles and conventions, they should be allowed to focus on the logic/feature.

Which means, rules that are purely presentational, example: `comma-dangle`, `indent`, `eol-last`, etc are not useful, prettier can take care of that.

Then, there are some best practices rules like [no-else-return](https://eslint.org/docs/rules/no-else-return), these are useful for reviewing your code and learning how to improve it, but I feel they are not worth breaking your build/not shipping your feature.

Lastly, there are rules that try to find potential bugs (example: [no-unreachable](https://eslint.org/docs/rules/no-unreachable)), these are super useful! As they actually point out mistakes that you might have made.

But again, happy with whatever you guys decide 😄

**Comment by nitin42** [comment]
IMO.. if you want your codebase to adapt a code standard, you should use eslint (not necessary though).

**Comment by nitin42** [comment]
But it's a good practice so @SaraVieira may be you can start working on a PR 😄

**Comment by SaraVieira** [comment]
I'll start working on it with just airbnb and prettier 🎉
Thanks for the feedback guys!

**Comment by palashmon** [comment]
In addition to eslint, do you think we need to add [.editorconfig](http://editorconfig.org/) to help define and maintain consistent coding styles between different editors and IDEs?

Regards!

**Comment by SaraVieira** [comment]
That is a great idea, I'll put that in the PR too ☺️

**Comment by ForsakenHarmony** [comment]
you should probably use airbnb-base because we don't have react code

**Comment by SaraVieira** [comment]
@forsakenHarmony so standard and prettier?

**Comment by SaraVieira** [comment]
Didn't remember that airbnb is focused for react

**Comment by ForsakenHarmony** [comment]
just [airbnb-base](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base)

**Comment by SaraVieira** [comment]
Okay! On it!
