### ISSUE TITLE
Add a Slack team

### ISSUE THREAD

**Issue by LeGfrey** [siddharthkp/bundlesize#117]
Hi guys,

I was thinking about creating a slack team to chat with more ease than on Github issue especially to know more each other, ask question / help or welcome new people 😄 

Please tell me what you think about that 👍

**Comment by ForsakenHarmony** [comment]
wish there was something other than slack and gitter

**Comment by palashmon** [comment]
Nice idea. I am already on slack and its nice. For new users, posting code might be difficult as first but its same as github.

**Comment by ForsakenHarmony** [comment]
if only slack wouldn't require one account per team ...

**Comment by siddharthkp** [comment]
> wish there was something other than slack and gitter

I really want to try out spectrum.chat 😄  if you guys are up for it!

@mxstbr is a co-founder and it looks super pretty!

**Comment by siddharthkp** [comment]
I jumped the gun and created a community on spectrum: https://spectrum.chat/bundlesize

Check it out, see if you like it 😄

**Comment by palashmon** [comment]
I jumped the gun and created our first community thread :smile:

**Comment by kuldeepkeshwar** [comment]
created a [slack team](https://bundlesize.slack.com), in case we are moving to slack

**Comment by ForsakenHarmony** [comment]
@kuldeepkeshwar you're gonna have to hand over ownership if we do

**Comment by hawkins** [comment]
Spectrum is neat but lacks code snippet support as far as I can tell? My vote is for slack, added bonus is it feels like most other libraries and communities already use it 🤷‍♂️

**Comment by siddharthkp** [comment]
@kuldeepkeshwar How do join the slack team? 🤔

**Comment by siddharthkp** [comment]
> My vote is for slack

Agreed 😄

**Comment by kuldeepkeshwar** [comment]
@siddharthkp yesterday I posted the invite link in ` spectrum.chat` , check `Welcome to bundlesize!` thread

**Comment by reznord** [comment]
Can just drop the link here 😄

**Comment by kuldeepkeshwar** [comment]
https://join.slack.com/t/bundlesize/shared_invite/MjMyNTA0NjUwNzg5LTE1MDM4NjAxNjEtMjFjZThlZmIxMw

**Comment by kamleshchandnani** [comment]
I guess most of us are up for slack. Hence closing this
Added slack url to the contributing.md guide https://github.com/siddharthkp/bundlesize/commit/48cd121e5758a5dbe4aa65cd99cab97217b2b98d

**Comment by cg-cnu** [comment]
Should we add the slack link to the `contributors.md` ?

**Comment by reznord** [comment]
I like the idea, what about adding it in `README` along with the badges?

**Comment by cg-cnu** [comment]
I was looking for it; https://shields.io/ dosen't seems to have a slack badge support. 
The other option available is https://github.com/rauchg/slackin.

**Comment by cg-cnu** [comment]
And its mostly for the contributors, I feel it will can be better added in `contributors.md` as an invitation to join and `readme.md` is mostly for general users. what say! correct me if am wrong 😄

**Comment by reznord** [comment]
That's more like restricting the people to join a community/group. No matter what project you take for eg: `babel` or `redux-forms` or any other library, they put the badges in the README itself.

**Comment by cg-cnu** [comment]
ah... got it! That make sense. For now, we can add just the link in readme. 
Later we can setup slackin. btw, this is how the badge looks like https://cldup.com/jWUT4QFLnq.png

**Comment by karanjthakkar** [comment]
I'm with @reznord on this one. It should be in the README. If we can't find a badge then I guess even a link could work. :)

**Comment by cg-cnu** [comment]
@karanjthakkar Yes, even I agree with @reznord 😃

**Comment by kamleshchandnani** [comment]
So it should be in borh contributors and readme?

**Comment by reznord** [comment]
Just in `README`

**Comment by cg-cnu** [comment]
should I add the link 😄

**Comment by palashmon** [comment]
We can create a custom badge and just add the link to it, so that it would look consistent with other badges.

**Comment by palashmon** [comment]
Using this site: https://rozaxe.github.io/factory/

**Comment by cg-cnu** [comment]
True, but I don't think slack provides a permanent invite link. So, we need to setup [slackin](https://github.com/rauchg/slackin). That will provide the badge as well 🙂

**Comment by cg-cnu** [comment]
@palashmon @reznord @kamleshchandnani Created a new issue. Lets move the converstaion here... #132
