### ISSUE TITLE
Shouldn't `yarn.lock` be ignored?

### ISSUE THREAD

**Issue by ForsakenHarmony** [siddharthkp/bundlesize#119]
As in remove the `.`?

https://github.com/siddharthkp/bundlesize/blob/5b7d0795b52c590425da3a978d175eb0dbb2d97b/.gitignore#L61

**Comment by reznord** [comment]
There's a `.` before the `yarn.lock` there. That is the issue

**Comment by ForsakenHarmony** [comment]
indeed

**Comment by tohjustin** [comment]
@ForsakenHarmony Sorry wasn't sure if you're planning to create a PR to fix this, will gladly abandon mine if you want to do it instead >_<
