### ISSUE TITLE
[Discussion] Adding a npm stats badge in readme

### ISSUE THREAD

**Issue by palashmon** [siddharthkp/bundlesize#123]
_Note: This is not a issue actually but more of a open discussion regarding a new readme npm stats badge._

Hi Everyone,

Just wanted to know, if you guys think we can add a badge to show no. of downloads/month like:

[![NPM Stats](https://img.shields.io/npm/dm/bundlesize.svg)](http://npm-stat.com/charts.html?package=bundlesize&from=2017-06-20)

If you click the badge, you can visit to npm-stat page which will show the full stats also. Currently we have around 12k downloads/month and I think we need to show this impressive stats to the world, right on the readme page.

What you guys think?

Regards!

**Comment by vs1682** [comment]
I think it's a great idea. Let's do that.
