### ISSUE TITLE
[Feature] Automate package publishing using semantic-release

### ISSUE THREAD

**Issue by palashmon** [siddharthkp/bundlesize#124]
**Do you want to request a *feature* or report a *bug*?**
- feature

**What is the current behavior?**
```
   npm version major
   git push origin master --tags
   npm publish
  ```
You manually decide what the next version is. You have to remember what major, minor and patch means. You have to remember to push both commits and tags. You have to wait for the CI to pass.

**If the current behavior is a bug, please provide the steps to reproduce.**
- NA

**What is the expected behavior?**
```
git commit -m "fix: <message>"
git push
```
You describe the changes you’ve made. A new version is automatically published with the correct version number.

**If this is a feature request, what is motivation or use case for changing the behavior?**
- **Motivation:** :package: :rocket: [fully automated package publishing](https://github.com/semantic-release/semantic-release)

**Please mention other relevant information.**
- node version: NA
- npm version: NA
- Operating system: NA
- bundlesize version: NA
- CI you are using: NA

**Comment by kuldeepkeshwar** [comment]
we can use [version-bump-prompt](https://www.npmjs.com/package/version-bump-prompt)

**Comment by siddharthkp** [comment]
This is interesting 🤔 

How does it decide what version to apply for pull requests? (which might have multiple commits, or might have one squashed commit)

**Comment by palashmon** [comment]
That is internally handled by semantic release using the commit-analyzer approach.
You can check out the default implementation [here](https://github.com/semantic-release/commit-analyzer/blob/master/src/index.js).

**Comment by palashmon** [comment]
Not sure what is the reason for this. Could you please open an issue here https://github.com/semantic-release/semantic-release, so that they can have a look into and provide some insight into it.
