### ISSUE TITLE
Logo on build info page failing to load

### ISSUE THREAD

**Issue by paulirish** [siddharthkp/bundlesize#125]
getting a 503 on the logo.

![image](https://user-images.githubusercontent.com/39191/29845550-1eb14282-8cc8-11e7-9c79-2991d3a3b2fd.png)

you could pull that via the https://rawgit.com/ cdn instead probably..

**Comment by SaraVieira** [comment]
Hello Paul! 

Thanks for the info, I'll get on fixing that in the morning ☺️

rawgit seems like a great idea I'll try that 🎉

**Comment by ForsakenHarmony** [comment]
503 seems like a weird error for that, can you access the link directly?

but yeah, rawgit is probably a good idea

**Comment by cg-cnu** [comment]
Hey guys! Thought its a simple one and gave it an attempt. Let me know if its fine 😄

**Comment by reznord** [comment]
@paulirish if I'm not mistaken, `rawgit` redirects to `raw.githubusercontent`.

**Comment by cg-cnu** [comment]
@kuldeepkeshwar @SaraVieira @reznord Thanks a lot for the help. You guys are awesome! 😃

**Comment by SaraVieira** [comment]
@paulirish Should be fixed in 0.14.3 🚀
