### ISSUE TITLE
Add Greenkeeper 

### ISSUE THREAD

**Issue by SaraVieira** [siddharthkp/bundlesize#127]
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the current behavior?**
If someone does npm install they may get a different e lock than the one on master because our packages may not be updated

**What is the expected behavior?**
Have a bot like greenkeeper telling us we need to update stuff 

**If this is a feature request, what is motivation or use case for changing the behavior?**
https://github.com/siddharthkp/bundlesize/pull/126

**Comment by SaraVieira** [comment]
@reznord @ForsakenHarmony are you guys okay witrh this ?

**Comment by kuldeepkeshwar** [comment]
@SaraVieira 👍

**Comment by SaraVieira** [comment]
Turns out I can't already asked siddharthkp

**Comment by ForsakenHarmony** [comment]
sure
so wait, can we or no?

**Comment by SaraVieira** [comment]
I don't have permission to add it, it needs to be @siddharthkp

**Comment by siddharthkp** [comment]
Whoops, I don't have my laptop with me. I'll have to come back to this in a couple of days 🙂

**Comment by ForsakenHarmony** [comment]
no worries, don't think it's urgent

**Comment by SaraVieira** [comment]
Na, take your time :)

**Comment by siddharthkp** [comment]
Done!!
