### ISSUE TITLE
Remove package-lock.json

### ISSUE THREAD

**Issue by reznord** [siddharthkp/bundlesize#128]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Right now we are including `package-lock.json` in the repo and adding it will just make the things harder like keeping the `package-lock.json` up to date every time. I agree that using `package-lock.json` makes it easy and happy for users with `npm>5`. But this is a trade-off which we have to consider.

**What is the expected behavior?**
Remove `package-lock.json` from the repo.

**Please mention other relevant information.**
- node version: 8.2.1
- npm version: 5.x
- Operating system: macOS

**Comment by palashmon** [comment]
I think we can remove it. But, again as @SaraVieira has mentioned in https://github.com/siddharthkp/bundlesize/pull/126#issuecomment-325933500, we might or might not get issues in the future in Travis CI. 

I think this has to be a ongoing test process to figure if it would be future proof like:
1. Create a test repo or branch for this purpose.
1. Add package-lock.json to .gitignore on this branch
1. Add few dependencies and dev depedencies in `package.json`.
1. Add few commits based on this new `package.json`
1. See if the CI build is passing.
1. Add few more dependencies and dev depedencies in `package.json` and remove some of the old ones.
1. Repeat steps 4-5
