### ISSUE TITLE
0.14.3 install bug w/ init-status

### ISSUE THREAD

**Issue by scttcper** [siddharthkp/bundlesize#130]
Anyone else getting this?

```sh
❯ npm i bundlesize -D
npm ERR! path /Users/scoope7/ngx-trend/node_modules/bundlesize/src/init-status.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/scoope7/ngx-trend/node_modules/bundlesize/src/init-status.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/scoope7/.npm/_logs/2017-08-31T17_22_26_445Z-debug.log
```
**Please mention other relevant information.**
- node version  
v8.3.0
- npm version  
5.4.0
- Operating system  
osx
- bundlesize version  
0.14.3
- CI you are using  
travis, but this is on my local

already tried verifying npm cache and then i cleared it just because. Using 0.14.2 for now.

**Comment by ForsakenHarmony** [comment]
yeah, that file seems to have gotten deleted but is in one of the scripts

https://github.com/siddharthkp/bundlesize/blob/e33b238807b70706394486e2f85cbe6c4e916ed2/package.json#L12

**Comment by ForsakenHarmony** [comment]
got removed in [this commit](https://github.com/siddharthkp/bundlesize/commit/9e4880be3acaa11fd88ef8f219252a3836f18460), probably by accident
