### ISSUE TITLE
provide slack group invite link

### ISSUE THREAD

**Issue by cg-cnu** [siddharthkp/bundlesize#132]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
No slack invite!

**If this is a feature request, what is motivation or use case for changing the behavior?**
Provide a link / badge for inviting to the slack group.

**Comment by reznord** [comment]
This is no feature 😅 and let's continue the discussion in #117. No need of opening multiple issues for the same thing 😄

**Comment by cg-cnu** [comment]
Errr... ok! 😆
