### ISSUE TITLE
Compression level option

### ISSUE THREAD

**Issue by marapper** [siddharthkp/bundlesize#138]
**Feature**

***What is the current behavior?***

Uses default level of compression that hardcoded in `gzip-size`/

***What is the expected behavior?***

This [PR](https://github.com/sindresorhus/gzip-size/pull/8) will add zlib options to function arguments.

So we can add option `level`

```
  "bundlesize": [
    {
        ...
        "maxSize": "30KB",
        "level": 6
```

***If this is a feature request, what is motivation or use case for changing the behavior?***

In many real cases we use lower gz compression level for assets (js, css, html) to fasten compression/decompression. So with this options we could check real size restrictions.

**Comment by siddharthkp** [comment]
Simlar to https://github.com/siddharthkp/bundlesize/issues/140

Merging the 2 issues
