### ISSUE TITLE
Flag to disable gzip

### ISSUE THREAD

**Issue by marapper** [siddharthkp/bundlesize#139]
**Feature**

***What is the current behavior?***

`maxSize` is max size of gzipped files.

***What is the expected behavior?***

Bundlesize can be used not only for checking assets size. Sometimes it could be helpfull if we have option like `maxRealSize`.

```
fs.statSync(path).size
```

**Comment by siddharthkp** [comment]
I think the answer to this lies in https://github.com/siddharthkp/bundlesize/issues/140#issuecomment-335371345 as well 😄 

We can look at an optional flag to disable compression

**Comment by keirlawson** [comment]
would a PR be welcome for this?

**Comment by siddharthkp** [comment]
@keirlawson Yep, updated the title as well.

A pull request that adds a flag to disable gzip is welcome 😄

**Comment by keirlawson** [comment]
my though was more to add a parallel option, like `maxDiskSize`?

**Comment by siddharthkp** [comment]
I'm not keen on adding that because of: https://github.com/siddharthkp/bundlesize/issues/140#issuecomment-335371345

**Comment by siddharthkp** [comment]
That solves 2 problems together by passing control to the user. Is there a use case where you would want to compare the real file size instead of gzipped (this comes with the assumption that you should first use gzip on your servers if you are trying to optimize for performance)

**Comment by keirlawson** [comment]
In my case I sadly don't have control of the server environment, so can't be certain the file will
be gzipped, hence the size on disk being more interesting for me

**Comment by siddharthkp** [comment]
Interesting use case, although users will be served gzipped, right? Is that not a fair assumption?

Even so, a disable compression flag will give you size on disk that you are looking for 😄
