### ISSUE TITLE
More obvious name for upper limit/threshold

### ISSUE THREAD

**Issue by siddharthkp** [siddharthkp/bundlesize#14]
`Threshold` feels like it's the delta, whereas we need an absolute amount, `max size`?

**Comment by reznord** [comment]
@siddharthkp I'd like to take this

**Comment by siddharthkp** [comment]
Ideas on name?

**Comment by reznord** [comment]
> Ideas on name

`maxSize` makes total sense in this case.

**Comment by siddharthkp** [comment]
cool, go for it! 

please keep backward compatibility in code but remove it from docs :)
