### ISSUE TITLE
Separate checks / storage / reporters

### ISSUE THREAD

**Issue by marapper** [siddharthkp/bundlesize#141]
**Feature**

***What is the current behavior?***

`files` calculate size

`reporter` check size, prepare result to output and send data to bundlesize-store.now.sh

***What is the expected behavior?***

1. Gathering data (realSize, pass/fail status) can be extracted to "checks" part. e.g. for https://github.com/siddharthkp/bundlesize/issues/140

2. API call (saving and getting `master` results) can be extracted to "storages". It could be *optional* for private repos or self-hosted.

3. In some cases we need file / table cli reporters. May be average size for repo in which we build a few bundles simultaneously. Creating of badges can be extracted to separated reporter too.

**Comment by siddharthkp** [comment]
@marapper, sounds good!

Does it solve an immediate problem?

**Comment by palashmon** [comment]
Closing this issue for now because it has not had recent activity. Thank you for your contributions.
