### ISSUE TITLE
Fuzzy comparison

### ISSUE THREAD

**Issue by marapper** [siddharthkp/bundlesize#142]
*bug*

**What is the current behavior?**

file.js = 1054 bytes
`maxfile` = 1KB

Expected message: `FAIL  ./src/file.js: 1kB < maxSize 1kB`
Actual: `PASS  ./src/file.js: 1kB < maxSize 1kB`

file.js = 1056 bytes
`maxfile` = 1KB

Expected message: `PASS  ./src/file.js: 1kB < maxSize 1kB`
Actual: `FAIL  ./src/file.js: 1kB < maxSize 1kB`

**What is the expected behavior?**

1. It's actually `<=` for now

2. When  `maxSize` is KB/MB value then

- maxSize should be used for strict inequality.
- OR file should PASS when it's size is between 1KB and 1.1KB (and it should be echoed in message)

**Comment by siddharthkp** [comment]
@marapper Great catch!!

Would you like to work on this? 

[CONTRIBUTING.md](https://github.com/siddharthkp/bundlesize/blob/master/CONTRIBUTING.md) is a good place to start. And of course, we are here to discuss the details + implementation and help you along the way!

**Comment by palashmon** [comment]
Closing this issue for now because it has not had recent activity. Thank you for your contributions.

**Comment by khangsfdc** [comment]
workaround for this is to use bytes instead of kilobytes for the maxSize.  You can obtain the exact bytes by running with --debug flag.
