### ISSUE TITLE
Features suggestions?

### ISSUE THREAD

**Issue by reznord** [siddharthkp/bundlesize#144]
More of a query for what features what we are going to add?

What all features would you like to add more to bundlesize? Any sort of inputs would be welcome

**Comment by ForsakenHarmony** [comment]
we have a couple in [Issues](https://github.com/siddharthkp/bundlesize/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature+request%22)

**Comment by reznord** [comment]
Forgot that there is a feature-request label exists 😅
