### ISSUE TITLE
Size in "checks have passed" interface

### ISSUE THREAD

**Issue by scttcper** [siddharthkp/bundlesize#149]
<img width="545" alt="screen shot 2017-09-24 at 12 43 19 pm" src="https://user-images.githubusercontent.com/1400464/30786143-5aa0c5b6-a126-11e7-86c6-3bd95dc0e683.png">

On the interface when you click the check on github. Others like codecov put a percentage, bundlesize says good job! I was wondering if the size or something more useful could be there.

**Comment by siddharthkp** [comment]
@scttcper Great idea!

This makes a lot of sense when there are multiple files. Would you like to work on this? 

[CONTRIBUTING.md](https://github.com/siddharthkp/bundlesize/blob/master/CONTRIBUTING.md) is a good place to start. And of course, we are here to discuss the implementation and help you along the way!

**Comment by scttcper** [comment]
#197 has what i wanted
