### ISSUE TITLE
Compare against branch other than master.

### ISSUE THREAD

**Issue by threehams** [siddharthkp/bundlesize#154]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Bundle size comparisons are done against master. This is hardcoded.

**If this is a feature request, what is motivation or use case for changing the behavior?**
We use [https://datasift.github.io/gitflow/IntroducingGitFlow.html](GitFlow) for managing releases, where feature branches are merged into a separate branch before being packaged up into releases. Because of this, it's much more useful to compare the current branch against the head branch (in this case, develop).

The current configuration doesn't allow for any extra keys (it's an array of objects). Should this be done as an environment variable since it's only really relevant for CI?

**Please mention other relevant information.**
- bundlesize version
0.14.1
- CI you are using
CircleCI

I can submit a PR for this, would just like to get a 👍  for the idea and approach.

**Comment by SaraVieira** [comment]
@threehams this is a very good point! I would live to see this happen so if you could a PR that would amazing 🙌

Let us know if you find any issues or need help in the PR 😄

**Comment by threehams** [comment]
What do you think of the question above?

> The current configuration doesn't allow for any extra keys (it's an array of objects). Should this be done as an environment variable since it's only really relevant for CI?

**Comment by siddharthkp** [comment]
I think an easy way of achieving this without breaking backward compatibility would be to introduce a new optional key `bundlesize-config` right next to `bundlesize` in `package.json`

We did discuss having a separate config file [here](https://github.com/siddharthkp/bundlesize/issues/33#issuecomment-313059745), but I don't think we need it yet.

**Comment by sethbattin** [comment]
This is the goal I had in mind when submitting https://github.com/siddharthkp/bundlesize/issues/173 (spoilers I work with David).  `"master"` is [currently hardcoded](https://github.com/siddharthkp/bundlesize/blob/master/src/reporter.js#L19), but if it were drawn from config it could be any base branch or merge target.

I think this idea is compatible with using ENV vars, too.  The `config` object could be in charge of all the data sources.

**Comment by Haroenv** [comment]
Branch target would make a lot of sense according to me, because master has some flaky integration tests in my case, which means that bundlesize can't be run there

**Comment by sethbattin** [comment]
@Haroenv, I had the same issue, so I implemented it in a fork: https://github.com/sethbattin/bundle-report/blob/parallel-dev/src/default.bundlereport.rc#L15

The fork also does config file loading, but the above setting can go into package.json as well.

**Comment by palashmon** [comment]
Closing this issue for now because it has not had recent activity. Thank you for your contributions.
