### ISSUE TITLE
pass in glob pattern, but only get report for 1 file

### ISSUE THREAD

**Issue by lmj0011** [siddharthkp/bundlesize#157]
**Do you want to request a *feature* or report a *bug*?**
report a *bug*

**What is the current behavior?**
glob patterns seem to not work with the bundlesize cli tool

**If the current behavior is a bug, please provide the steps to reproduce.**

pass in a glob pattern into the bundlesize command. (see screenshots for steps)

![err2](https://user-images.githubusercontent.com/9396189/31305721-2e579694-ab06-11e7-804b-56fd23532dcc.png)

![err3](https://user-images.githubusercontent.com/9396189/31305723-30b30450-ab06-11e7-9503-4fb747224284.png)

- contents of `src/`
![err1](https://user-images.githubusercontent.com/9396189/31305720-2b14f440-ab06-11e7-96d7-6060af818f85.png)

**What is the expected behavior?**

I was expecting 10 outputs, 1 for each file in the `src` directory

**Please mention other relevant information.**
- node version
7.10.0

- npm version
4.2.0

- Operating system
Ubuntu 16.04.3 LTS (xenial)

- bundlesize version
0.15.2

- CI you are using
none

**Comment by siddharthkp** [comment]
@lmj0011 Nice catch!

Turns out you can't get multiple files with commander (or maybe we're using it wrong)

Ref: https://github.com/siddharthkp/bundlesize/blob/master/src/config.js#L14-L28

Thanks for taking the time to report the issue, we'll fix it!

**Comment by siddharthkp** [comment]
@lmj0011 Would you like to work on this? 

[CONTRIBUTING.md](https://github.com/siddharthkp/bundlesize/blob/master/CONTRIBUTING.md) is a good place to start. And of course, we are here to discuss the details + implementation and help you along the way!

**Comment by lmj0011** [comment]
sure, I can take a look at it when I have time

**Comment by tdeschryver** [comment]
I think this might be a bash problem.
When running `node index.js -f ./src/*.js` on the normal windows cmd, it shows all the files.
When running on windows bash it just outputs the first file (the other files are accessible via `program.args`), when running  `node index.js -f './src/*.js'` it also shows all the files.

I don't know certain but maybe bash has a glob like system built in? 

Would it be an option to discard the `-f` option and make it like `bundlesize ./src/*.js`?
Would look like:
```
if (program.args) {
  cliConfig = program.args.map(path => ({ path, maxSize: program.maxSize }))
}
```

**Comment by siddharthkp** [comment]
hmm, I think we'll have to replace this with a more explicit file read.

side note: I'm not sure if sum of sizes is a useful metric, because bundles are usually loaded in parallel, you should optimise for the slowest request

**Comment by lmj0011** [comment]
@tdeschryver is right, BASH is parsing the glob before it gets handled in the node script.

My suggestion would be to make a note of quoting the glob path on the cli
https://github.com/siddharthkp/bundlesize#cli

see: https://medium.com/@jakubsynowiec/you-should-always-quote-your-globs-in-npm-scripts-621887a2a784

**Comment by siddharthkp** [comment]
@lmj0011 updated the readme for "quotes"

**Comment by styfle** [comment]
@siddharthkp I agree with @tdeschryver...
I thought the glob pattern was going to sum the size of the matched files to see if it exceeded the given size.

Is this feature implemented already or is there a feature request for this already?

**Comment by siddharthkp** [comment]
> I thought the glob pattern was going to sum the size of the matched files to see if it exceeded the given size.

Nope, sum of files is not a useful metric.

Here's the explanation: https://github.com/siddharthkp/bundlesize/issues/205#issuecomment-373604616
