### ISSUE TITLE
Idea: Remove the need for Firebase store

### ISSUE THREAD

**Issue by Furizaa** [siddharthkp/bundlesize#16]
I thought about the fact that the tool sends the bundle size information to a Firebase store to make comparisons across builds and how that can pull off possible users. I then began to search for alternatives - and I think I have found one:

For simple cli usage a run could simply store the result as a JSON file that compares against itself on rerun. Nothing special here.

When the tool is ran on a CI environment, it has to be configured in a way that this JSON result is stored in a opinionated or configured place in the build artifacts that then will be accessed via the CI tools API. With this in place we could compare against the latest master build or even compare against the target branch of a pull request.

With CircleCi this is a non issue. The API is in place and has all necessary endpoints to pull this of. But I'm not sure about travis. In my 5 minutes of googling I didn't find a way to easily access build artifacts other than a direct S3 connection. Do you have insights on this?

**Comment by siddharthkp** [comment]
what's the problem you're trying to solve?

If the file doesn't live in the repo, might as well be in firebase /shrug

**Comment by siddharthkp** [comment]
> I thought about the fact that the tool sends the bundle size information to a Firebase store to make comparisons across builds and how that can pull off possible users.

Why would that be? The user does not have to sign up for firebase. bundlesize internally uses firebase

**Comment by Furizaa** [comment]
Nah it's OK. After thinking about it some more I now also see the possibilities this could offer. Like a service that plots bundle size over time and whatnot. The only problem I still see is that it's a external point of failure that could break the build in case if it's offline. But I don't think that is a big problem and can be circumvented by failing gracefully.

**Comment by siddharthkp** [comment]
> service that plots bundle size over time

that's what i have my eyes on 👀 

> it's a external point of failure that could break the build in case if it's offline

so is your CI environment (travis/circle), I have taken the assumption that these CI will always have internet, hopefully that works out fine.
