### ISSUE TITLE
Add 'short name' option to config

### ISSUE THREAD

**Issue by erichdev** [siddharthkp/bundlesize#161]
**Do you want to request a *feature* or report a *bug*?**
Feature request: Add a 'short name' option to the config

**What is the current behavior?**
The status posted to Github contains the full filepath/filename. Long filenames cause the status to get truncated.

**What is the requested behavior?**
If a 'short name' is provided in the config, use the short name in the message posted to Github. Otherwise, default to the full filename.

**If this is a feature request, what is motivation or use case for changing the behavior?**
With long filepaths/filenames, the Github status gets truncated, hiding the size comparison. You have to either click the 'Details' link or hover over the status for the actual size comparison to appear.

**Please mention other relevant information.**
- bundlesize version: 0.15.2

**Comment by siddharthkp** [comment]
This is a really nice detail! thanks for filling an issue.

Do you think this is something that we can infer and give to everyone instead of asking for an additional config variable?

**Comment by erichdev** [comment]
Curious how it would be inferred? Do you mean something like using the filename only and not the full filepath?

**Comment by siddharthkp** [comment]
Yep, if shortening the name doesn't lead to clashing file names, then we should do it.

There's a discussion around this here: 
https://github.com/siddharthkp/bundlesize/pull/81#issuecomment-325182045

**Comment by erichdev** [comment]
Oh awesome. Seems like the ball is already rolling on that. I think it'd still be helpful to have an optional config item to manually set the display name in case the filename is long even if the full path is omitted and in case there are duplicate filenames (e.g. multiple packages output 'bundle.js'). I think that'd be helpful for the Github Status UI since Github restricts the number of characters 👍

**Comment by vs1682** [comment]
@siddharthkp can we do something like showing a shortpath (filename + parentName) for the file and full path on hovering the shortPath.

------
![shortpathbundlesize](https://user-images.githubusercontent.com/5151881/31710830-d111b8cc-b413-11e7-8ad0-b85721874db1.gif)

**Comment by siddharthkp** [comment]
@vs1682, yep that's the idea. Check https://github.com/siddharthkp/bundlesize/pull/166

**Comment by palashmon** [comment]
Closing this issue for now because it has not had recent activity. Thank you for your contributions.
