### ISSUE TITLE
Add a way to move bundlesize configuration

### ISSUE THREAD

**Issue by Johann-S** [siddharthkp/bundlesize#162]
Hi,

First of all thank you for this awesome project :+1: 

Currently on Bootstrap we use bundlesize, but we have (IMO) a huge [package.json](https://github.com/twbs/bootstrap/blob/v4-dev/package.json) so it would be convenient to be able to add a new config file, for example `.bundlesizeconfig`

**Comment by siddharthkp** [comment]
I'm so happy that bootstrap uses this!

`.bundlesize.yml` is something that I have thought about multiple times.

Here's how I look at it in order of priority:

a. CLI args
b. `bundlesize` object in `package.json`
c. `.bundlesize.yml` (this will help us make some breaking changes to the config to enable more feature flags)

However, this is not something I can pick up immediately.

Would you like to take a shot at it? [This is a good place to start](https://github.com/siddharthkp/bundlesize/blob/master/CONTRIBUTING.md#structure).

**Comment by Johann-S** [comment]
Sure :+1: but when that's an other question :smile: 
I'll add that to my todolist

**Comment by sethbattin** [comment]
Added https://github.com/siddharthkp/bundlesize/issues/173 re: `package.json` object settigns

**Comment by siddharthkp** [comment]
Implemented in https://github.com/siddharthkp/bundlesize/pull/316 and published in 0.18.0 🎉 

Check out [README for details](https://github.com/siddharthkp/bundlesize#configuration)
