### ISSUE TITLE
Dedup files from config

### ISSUE THREAD

**Issue by siddharthkp** [siddharthkp/bundlesize#164]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
bundlesize picks up the same file twice because of how globs work.

```
dist/vendor-*.js 30Kb
dist/*.js 90Kb 
```

`vendor-*.js` will be picked up twice with different sizes.

**If this is a feature request, what is motivation or use case for changing the behavior?**

I started thinking about this after looking at @tizmagik's [tweet](https://twitter.com/tizmagik/status/892212229575241728)

> But sometimes new chunks appear and others get optimized out & not captured by bundlesize. Just gotta keep 👀 on

A way that bundlesize can enable this is by allowing blanket conditions that don't conflict with specific ones.

```
dist/vendor-*.js 30Kb
dist/*.js 90Kb 
```
`vendor` should only be compared with 30Kb, the rest of the files in `dist/*` should be compared with 90Kb

**Comment by tizmagik** [comment]
Thanks @siddharthkp this is great! I might actually take this if I find some time this weekend 😁

> the rest of the files in `dist/*` should be compared with 90Kb

I wonder if it would make sense to compare _total size_ of the rest of the files with 90Kb, or if it should be _each_ of the rest of the files. I think it might make more sense to compare total size, but I could see a use case for comparing each.

Maybe we could support both? Something like a `maxSize` for comparing each and `totalSize` to compare total? What do you think?

**Comment by siddharthkp** [comment]
I don't think total size makes sense here because the way they will be served to the client, especially if the bundles are split by route.

Take this for an example:

```
dist/vendor.js 30Kb
dist/homepage.js 40Kb
dist/features.js 40Kb
```
Now adding a new page/bundle, something like `dist/about.js` should not start failing builds 😄
What we do want is that `dist/about.js` should follow the bare minimum quality metric (90Kb in this example) until someone configures it to a number that makes more sense for that page.

**Comment by tizmagik** [comment]
Sure yea that makes sense 👍

**Comment by marvinchin** [comment]
Is there still any interest in this issue? If there is, I'd like to take a shot at it!

**Comment by siddharthkp** [comment]
Hi @marvinchin, the feature still makes sense but I don't think I'll be able to review and merge it anytime soon, so I wouldn't recommend jumping on it

**Comment by ryanwilsonperkin** [comment]
I'd also be interested in helping out with this once there's time available to review and merge it. We're interested in using bundlesize, but currently blocked by this because we use chunk hashes which are affected by this issue.

**Comment by siddharthkp** [comment]
FYI, this is now implemented in [bundlesize2](https://github.com/siddharthkp/bundlesize2)
