### ISSUE TITLE
Please remove the postinstall opencollective ad

### ISSUE THREAD

**Issue by styfle** [siddharthkp/bundlesize#167]
**Do you want to request a *feature* or report a *bug*?**
Enhancement

**What is the current behavior?**
Show postinstall opencollective ad

**If the current behavior is a bug, please provide the steps to reproduce.**
```sh
npm install --save react-server-example-tsx@4.0.1
```

**What is the expected behavior?**
Expected no output

**If this is a feature request, what is motivation or use case for changing the behavior?**
It is confusing the the user who is not directly installing bundlesize but it happens to be a dependency of a package the are installing.

**Please mention other relevant information.**
- node version 8.7.0
- npm version 5.4.2
- Operating system macOS 10.13
- bundlesize version 0.15.2

I think it's great that you are bringing in money for working on open source software, but the post install script is kind of a nasty way to do it because it propagates everywhere. Any package that depends on `bundlesize` is going to display that message at install so at this time, I'm going to remove it as a dependency from my repo, [react-server-example-tsx](https://github.com/styfle/react-server-example-tsx), to avoid confusing users who are trying to learn React + TypeScript.

**Comment by SaraVieira** [comment]
@siddharthkp

**Comment by siddharthkp** [comment]
@styfle Thanks for your feedback!

Good point, I have removed it and published a minor `0.15.3`

**Comment by styfle** [comment]
Thanks for the quick response!
