### ISSUE TITLE
Javascript API

### ISSUE THREAD

**Issue by BarryThePenguin** [siddharthkp/bundlesize#179]
Feature

`bundlesize` is a cli tool that takes command line arguments as input

Current build tools that I'm using, include gulp and others, already provide a means of reading files from the filesystem. If `bundlesize` exposed an API I could use that with the bundled files I already hold in memory.

[src/files.js](https://github.com/siddharthkp/bundlesize/blob/master/src/files.js) already does most of the heavy lifting when it comes to reading files from the filesystem. It is also synchronous. Would you be open to exposing an API that can accept bundle contents as strings, buffers, or streams? And an API that is asynchronous?

**Comment by siddharthkp** [comment]
> Would you be open to exposing an API that can accept bundle contents as strings, buffers, or streams?

What benefit would that open up?

> It is also synchronous

`src/files.js` can be made async but it probably wouldn't lead to any perceivable performance benefit for < 100 files

**Comment by BarryThePenguin** [comment]
We have a seperate bundling process for our packages that doesn't happen on CI. It happens after the package has been published to npm.

As our CI process doesn't currently build bundles, we don't have any files on the filesystem to run bundlesize with. We could build a bundle in memory and pass it onto bundlesize if there was a javascript API.

This would save us the steps required to build a bundle, write to the filesystem, then run bundlesize as a seperate build step.

Some examples of API usage include

```js
pipe(
  gulp.src('./src/*.js'),
  bundle(),
  bundlesize(),
);
```

or

```js
pipe(
  request('https://unpkg.com/react/umd/react.production.min.js'),
  bundlesize(),
);
```

I'm happy to put together a PR. At the moment we've written our own version of `bundlesize` + `github-build` into our build tools and are looking at contributing back in some way 😀

**Comment by palashmon** [comment]
Closing this issue for now because it has not had recent activity. Thank you for your contributions.
