### ISSUE TITLE
Add documentation on how to get bundlesize GitHub integration in generic CI

### ISSUE THREAD

**Issue by thiagogoncales** [siddharthkp/bundlesize#185]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
No documentation on how to integrate `bundlesize` with some generic CI

**If this is a feature request, what is motivation or use case for changing the behavior?**
I had to dig through https://github.com/siddharthkp/ci-env code base in order to find the required variables, which btw are 
- CI_REPO_OWNER
- CI_REPO_NAME
- CI_COMMIT_SHA
- BUNDLESIZE_GITHUB_TOKEN

With this, you can hook bundlesize up with Jenkins for instance, and get a bit closer to solving https://github.com/siddharthkp/bundlesize/issues/22

**Comment by jakebolam** [comment]
THANK YOU, THIS NEEDS TO BE IN THE DOCS

**Comment by siddharthkp** [comment]
@jakebolam Do you want to add it?
