### ISSUE TITLE
Support ignore pattern

### ISSUE THREAD

**Issue by walkerrandolphsmith** [siddharthkp/bundlesize#186]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I am not aware of an ignore pattern in the bundlesize configuration.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The ignore glob will ignore processing files that match the glob pattern.

**If this is a feature request, what is motivation or use case for changing the behavior?**
I have a monorepo and want to verify the size of each package is within the size limit.
```
"bundlesize": [
    {
      "path": "./packages/**/dist/index.js",
      "maxSize": "3 kB"
    }
  ]
```
This can test every artifact produced by the different packages, but my glob pattern also matches `/dist/index.js` within `node_modules` which is not ideal.

**Please mention other relevant information.**
- node version
8.6.0
- npm version
5.5.1
- Operating system
Mac OSX
- bundlesize version
0.15.3
- CI you are using
Travis CI

**Comment by walkerrandolphsmith** [comment]
I can accomplish my goal with the following config. Not sure if there are other use cases. Will close until one is identified.
```
"bundlesize": [
    {
      "path": "./packages/*/dist/index.js",
      "maxSize": "3 kB"
    }
  ]
```

**Comment by siddharthkp** [comment]
@walkerrandolphsmith bundlesize uses [glob](https://github.com/isaacs/node-glob) underneath which supports ignoring files :)

**Comment by robertwbradford** [comment]
I have the following
```
{
  "path": "packages/*/lib/**/*.js",
  "maxSize": "4.9 kB"
}
```
and am not seeing how to ignore a single `packages/foo/lib/cjs/index.js` file while still maintaining the other `*`s and `**`. I see in the `node-glob` package that its signature allows for an `options` arg which can contain information on ignored paths, but I'm not getting how to do that with a single string value for `path` here. Any help is appreciated.
