### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by rosskevin** [siddharthkp/bundlesize#190]
**Do you want to request a *feature* or report a *bug*?**
bug (3 builds attempted)

**What is the current behavior?**
500 error

```
$ npm run filesize
> react-apollo@2.0.4 filesize /home/travis/build/apollographql/react-apollo
> bundlesize
{ Error: Request failed with status code 500
    at createError (/home/travis/build/apollographql/react-apollo/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/travis/build/apollographql/react-apollo/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/home/travis/build/apollographql/react-apollo/node_modules/axios/lib/adapters/http.js:191:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  config: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: 
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.16.2' },
     method: 'get',
     url: 'https://bundlesize-store.now.sh/values?repo=apollographql/react-apollo&token=xxxomitedxxx',
     data: undefined },
```

**If the current behavior is a bug, please provide the steps to reproduce.**
travis ci build of PR https://github.com/apollographql/react-apollo/pull/1488

**What is the expected behavior?**
Success

**If this is a feature request, what is motivation or use case for changing the behavior?**
n/a

**Please mention other relevant information.**
- node version 8.9.3
- npm version 5.5.1
- Operating system ? travis linux container
- bundlesize version 0.15.3
- CI you are using travis

**Comment by karanjthakkar** [comment]
@rosskevin Looking at the url https://bundlesize-store.now.sh/values?repo=apollographql/react-apollo&token=xxxomitedxxx, I'm guessing it is because of zeit services facing some issues since the past few hours: https://twitter.com/zeit_status/status/946465466540797952 Things should go back to normal once that is sorted.

**Comment by rosskevin** [comment]
Just tried again - still 500. 

I'll just leave this open for others to find.  Once things are good feel free to close.

**Comment by karanjthakkar** [comment]
@rosskevin Can you give it a shot again? Looks like everything is back up! https://twitter.com/zeit_status/status/946597402483421184

**Comment by siddharthkp** [comment]
Yeah, there was a long downtime yesterday, wondering what should be our fall back mechanism, skip checks with a warning?

**Comment by rosskevin** [comment]
All good now
