### ISSUE TITLE
Allow bundlesize to be configured by a file rather than relying on package.json

### ISSUE THREAD

**Issue by debugme** [siddharthkp/bundlesize#206]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Configuration can only be read from package.json file

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
To be able to pass in configuration by specifying path to a file. 

For example: 

`$ bundlesize --config ./configs/bundlesize/config.json `

**If this is a feature request, what is motivation or use case for changing the behavior?**

Avoid cluttering up package.json

**Please mention other relevant information.**
- node version
- npm version
- Operating system
- bundlesize version
- CI you are using

**Comment by tdeekens** [comment]
I would love this feature too. This should be fairly easy to achieve with this package https://github.com/davidtheclark/cosmiconfig. It is for instance used in `jest-runner-eslint` among others. Would you be interested in a PR for this?

**Comment by Johann-S** [comment]
Related to: https://github.com/siddharthkp/bundlesize/issues/162

**Comment by siddharthkp** [comment]
Implemented in https://github.com/siddharthkp/bundlesize/pull/316 and published in 0.18.0 🎉 

Check out [README for details](https://github.com/siddharthkp/bundlesize#configuration)
