### ISSUE TITLE
Keep the size in check, without limiting it

### ISSUE THREAD

**Issue by bfred-it** [siddharthkp/bundlesize#21]
I love easily keeping track of a build size, but I don't necessarily need a low limit (e.g. for a Web Extension) that would force us to make dumb choices (i.e. change the code to be lighter but less readable) just to get a ✅

I _could_ set a high limit but seeing `30KB < 500KB threshold` feels like it's a race to reach it 😄 

What if it always passed the build and just showed `careful, 30% larger than master` so seemingly small dependencies can't fool us.

**Comment by siddharthkp** [comment]
> I could set a high limit but seeing 30KB < 500KB threshold feels like it's a race to reach it 😄

can you elaborate a little? this is my default solution, right now

**Comment by bfred-it** [comment]
I may be wrong but it can be read as: _"It's only 6% its maximum weight, don't worry about making it heavier"_

**Comment by siddharthkp** [comment]
ah, gotcha!

**Comment by reznord** [comment]
@bfred-it I'll explain what I understood from the discussion. Please correct me if I'm wrong.

So, right now when we include integrate bundlesize in travis, it is showing like this:

> ./dist.js: 3.6kb < threshold 4kb (0.2kb larger than master, careful)

This kinda sounds like a warning (Your bundle is reaching the maxSize limit).

What you are saying is, instead of making the showing the message like this, make the message more friendly saying:

"It's only 6% of its maximum weight, don't worry about making it heavier". Showing percentage because don't want to show a small difference because of deps.

So, if I'm not wrong, it is just a change in the text for the message.

**Comment by siddharthkp** [comment]
> "It's only 6% of its maximum weight, **don't worry about making it heavier**"

This was meant to be sarcasm 😄

**Comment by siddharthkp** [comment]
What @bfred-it was saying was, he does not want an absolute limit as it will make people write bad code just to make the tests pass.

However, he does see value in comparison with master. It's a good way of making sure you don't end up introducing bloat by accident.

**Comment by reznord** [comment]
> This was meant to be sarcasm 😄

Yeah, I understood that part. :P
In my opinion, it is better to make the message a bit more readable (instead of default 😛 )

**Comment by bfred-it** [comment]
@reznord no no, no one wants to make bundles bigger! 😅

The copy change would be a separate issue, I'm only advocating for an **option** not showing the upper limit:

* `"maxSize": "4 Kb"`: `./dist.js: 3.6Kb < threshold 4Kb (0.2Kb larger than master, careful!)`
* `"maxSize": undefined`: `./dist.js: 3.6Kb (0.2Kb larger than master, careful!)`

**Comment by reznord** [comment]
That's already been taken care of!!!

Will be pushing the remaining required changes today!!

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by siddharthkp** [comment]
Implemented in https://github.com/siddharthkp/bundlesize/pull/65 (`bundlesize@0.10.0`)

**Comment by siddharthkp** [comment]
@FezVrasta @bbenezech @bfred-it You guys would like this ^
