### ISSUE TITLE
Support for Jenkins

### ISSUE THREAD

**Issue by romainneutron** [siddharthkp/bundlesize#22]

**Comment by siddharthkp** [comment]
@romainneutron, i would love to add support for Jenkins, can you identify the environment parameters that are used in `src/environment.js` and how to test them.

**Comment by wbeard** [comment]
@siddharthkp I'm interested in helping here. I have a project at work that builds via Jenkins. I'd like to start displaying bundle/chunk sizes in our PRs, so ideally a `bundlesize` job could be triggered by a PR then run in jenkins and send back results to the PR.

Are there any known issues with private repos?

**Comment by siddharthkp** [comment]
@wbeard nope, should work as long as you have a token with access to the private repo

**Comment by wbeard** [comment]
@siddharthkp from first glance, Jenkins may be tricky. I've found some mappings from jenkins environment vars to the vars needed in `environment.js`, but they change depending on what set of plugins you're using. I'll try to open up a PR and see if I can test the changes on my side later today.

**Comment by wbeard** [comment]
Also, I really like what you're doing here. I've had some similar ideas around this. Would love to chat! I'm on twitter if you want to dm @thewillbeard.

**Comment by Daniel15** [comment]
I think you'd need to have an actual Jenkins plugin that executes the bundle size script in order to get the best integration experience. A Jenkins plugin could display the information directly on the permalink page for the build, or as an option in the sidebar.

**Comment by siddharthkp** [comment]
@Daniel15,

I don't know how Jenkins works 😓 

From what you're saying, anyone can make a plugin that runs the bundlesize cli, right? 

Is it possible to add github status as well? As long as commit sha and github token is exposed, we should be good

**Comment by wbeard** [comment]
@Daniel15 I think you're right. I got it working w/ Github Pull Request Builder, which was cool, but it doesn't have a good way to display the output of bundlesize back to the commit status.

**Comment by ptchand** [comment]
@wbeard Can you please let me know how (steps) to make it working?

**Comment by palashmon** [comment]
Closing this issue for now because it has not had recent activity. Thank you for your contributions.
