### ISSUE TITLE
bundle name is unknown

### ISSUE THREAD

**Issue by enapupe** [siddharthkp/bundlesize#24]
Hey, I really like where this project is going. Thanks for doing it.

I want to ask if there's any way to deal with unknown bundle file names because I'm using webpack and my bundle files are hashes. 
I also have another constraint: I currently generate 2 JS files - vendor and app specific.

Also, my test script is custom and has other commands how would I configure it to work with bundlesize?
Thanks

**Comment by siddharthkp** [comment]
Yes, `bundlesize` uses [`glob`](https://github.com/isaacs/node-glob) inside, so you can use

```
path: "dist/*.js"
```
or something more specific, like "dist/home-*.js"

**Comment by siddharthkp** [comment]
Although I don't know how well will it play with github status, worth a try though. Let me know if it doesn't work as expected.

**Comment by siddharthkp** [comment]
> Also, my test script is custom and has other commands how would I configure it to work with bundlesize?

You just need to run `bundlesize` as a shell command. If you can show me your code, I'll be helpful

**Comment by enapupe** [comment]
Maybe I could run it as a circleci custom step?

**Comment by siddharthkp** [comment]
> Maybe I could run it as a circleci custom step?

Yep, that totally works.

**Comment by siddharthkp** [comment]
If you want to run it programmatically through your code, you can probably just do this:

```js
require('bundlesize')
```

This should work as long as you run it from in the root directory.

**Comment by enapupe** [comment]
Oh I guess I got it now..
It's basically a tool that checks file size (after gzip) against a predefined threshold. If it exceeds the threshold it exits with 1.

I think that in my case I'd have to do it within my Dockerfile because that's the only place I actually build the front-end application.
Thanks!

**Comment by siddharthkp** [comment]
Yep
