### ISSUE TITLE
What does the bundlesize service need the commit message for?

### ISSUE THREAD

**Issue by felixfbecker** [siddharthkp/bundlesize#240]
When run, in addition to bundle size, the tool sends the commit message to the public bundlesize service. This is not mentioned in the readme, and the upload happens automatically when the environment variables contain a `GITHUB_TOKEN`, without a flag to disable it. Many companies will not be comfortable with sending all their commit messages to a public service on every build. It's not obvious to me why the tool would need this data to work properly. What is it used for?

https://github.com/siddharthkp/bundlesize/blob/062d5b3bfb996657bf98e1626c06c620df23b235/src/reporter.js#L133

**Comment by siddharthkp** [comment]
It's used for the `details` page.

> Many companies will not be comfortable with sending all their commit messages to a public service on every build

It's not saved anywhere in the bundlesize store, but we can make it optional. It probably doesn't add a lot of value

<img width="774" alt="screen shot 2018-08-28 at 6 01 53 pm" src="https://user-images.githubusercontent.com/1863771/44723027-79f67980-aaec-11e8-8937-0e72efa4cac5.png">

**Comment by felixfbecker** [comment]
Thanks for the response! I don't know how GitHub statuses work but how is it displayed on the details page if it's not stored?

I think it would be good if it was explained in the readme what data is sent and what is stored, for what purpose - by default one would assume only bundle sizes are sent.

**Comment by siddharthkp** [comment]
We pass it query params, so it's stored in a github status 

Example: [https://bundlesize-store.now.sh/build?info=%7B%22files%22%3A%5B%7B%22maxSize%22%3A...](https://bundlesize-store.now.sh/build?info=%7B%22files%22%3A%5B%7B%22maxSize%22%3A16384%2C%22path%22%3A%22.%2Fdist%2Fstyled-components.min.js%22%2C%22size%22%3A15595%2C%22compression%22%3A%22gzip%22%2C%22master%22%3A16648%7D%5D%2C%22repo%22%3A%22styled-components%2Fstyled-components%22%2C%22branch%22%3A%22no-tag-list-entry%22%2C%22commit_message%22%3A%22Merge%20697638b39e7d56e59db5a2ad28db334dc66cf886%20into%2002172dda26c2ce994cf9ef8ea973dc13c3ffee6c%22%2C%22sha%22%3A%22697638b39e7d56e59db5a2ad28db334dc66cf886%22%7D)

**Comment by liorheber** [comment]
Hi, sorry for reviving an old issue.
Can I look into making this parameter optional?

**Comment by siddharthkp** [comment]
@liorheber I wouldn't want you to spend too much time on it, I'm rewriting the backend and will just skip this bit

**Comment by liorheber** [comment]
Got it, thanks.
We're actually already on the beta branch, so looking forward to seeing this!
