### ISSUE TITLE
Errors with npm v6

### ISSUE THREAD

**Issue by felixfbecker** [siddharthkp/bundlesize#243]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`bundlesize` has `engines.npm` set to `^5.0.0`. This causes errors with npm v6:

![image](https://user-images.githubusercontent.com/10532611/45159038-00dedc80-b1e6-11e8-919e-4af8992fe4f7.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

npm install

**What is the expected behavior?**
No errors. Why does it need the engine field at all? 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information.**
- node version
- npm version v6
- Operating system
- bundlesize version
- CI you are using

**Comment by siddharthkp** [comment]
This is fixed now 👍
