### ISSUE TITLE
[Feature Request] Allow Multiple checks per PR

### ISSUE THREAD

**Issue by roopakv** [siddharthkp/bundlesize#251]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
right now if you have multiple files you are checking wiht bundlesize, only 1 check is added to a PR. would be nice to allow 1 per run on bundlesize.

If i run `bundlesize -f "dist/file_a.js` and then `bundlesize -f "dist/file_b.js` only file b is shown.

if i run `bundlesize` with both in my package it adds them up instead of adding 2 checks.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Itd be awesome to add one check each for file_a and file_b on the PR

**If this is a feature request, what is motivation or use case for changing the behavior?**

This makes it so that devs can see PR statuses right from within the PR

**Please mention other relevant information.**
- node version 8.9.1
- CI you are using - Circle CI

**Comment by siddharthkp** [comment]
Hi 👋 thanks for taking the time to file an issue

That's an intentional design decision to reduce noise, that's where the details page was born

Discussion here: https://github.com/siddharthkp/bundlesize/issues/55
