### ISSUE TITLE
Add support for config in a separate file (.bundlesizerc)

### ISSUE THREAD

**Issue by bniwredyc** [siddharthkp/bundlesize#256]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
bundlesize can be configured by package.json section or CLI

**If this is a feature request, what is motivation or use case for changing the behavior?**
I have a pretty large package.json and I want to put libs' configs in separate files like .jestrc, .prettierrc, .eslintrc and so on. I want to do it with bundlesize too like this:
https://gist.github.com/bniwredyc/16a2e95ac06be090561710b0d9423680

If approved I will implement it myself.

**Comment by siddharthkp** [comment]
Implemented in https://github.com/siddharthkp/bundlesize/pull/316 and published in 0.18.0 🎉
