### ISSUE TITLE
Allow support for node 10

### ISSUE THREAD

**Issue by roopakv** [siddharthkp/bundlesize#261]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

can't install bundlesize if using node 10

**If the current behavior is a bug, please provide the steps to reproduce.**

- install node 10
- use bundlesize with node 10

**What is the expected behavior?**

Support node 10

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information.**
- node version 10.13.0
- npm version 6.4.1
- Operating system MacOSX
- bundlesize version latest
- CI you are using circleci

**Comment by XhmikosR** [comment]
@palashmon: this can be closed
