### ISSUE TITLE
Get package not exist issue for har-validator@5.1.2

### ISSUE THREAD

**Issue by ryancat** [siddharthkp/bundlesize#263]
Bug

Install bundlesize will further install har-validator version 5.1.2 on its dependency. Currently there is an issue for that version https://github.com/ahmadnassri/node-har-validator/issues/113 which prevent us from running `npm install`.

- node version 8.11.1
- npm version 5.4.2
- Operating system Linux
- bundlesize 0.17.0
- CI you are using Bamboo

**Comment by siddharthkp** [comment]
Hi 👋 

I believe `har-validator` is not part of the latest version. Feel free to comment back if you still face this problem
