### ISSUE TITLE
GITHUB_TOKEN is used instead of BUNDLESIZE_GITHUB_TOKEN when present

### ISSUE THREAD

**Issue by oliverviljamaa** [siddharthkp/bundlesize#264]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
`GITHUB_TOKEN` environment variable (although undocumented) is used instead of `BUNDLESIZE_GITHUB_TOKEN` when present. This results in `bundlesize` checks being authored by the owner of `GITHUB_TOKEN` rather than the owner of `BUNDLESIZE_GITHUB_TOKEN` (causing the wrong avatar and issues with the message).

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Set `GITHUB_TOKEN` as your personal access token (created here: https://github.com/settings/tokens) in CI.
2. Set `BUNDLESIZE_GITHUB_TOKEN` as the `bundlesize` token (retrieved as a result of authorizing the `bundlesize` application) in CI.
3. Run `bundlesize` in CI.
4. The GitHub status check will be authored by your account, not `bundlesize`, as it should.

**What is the expected behavior?**
`BUNDLESIZE_GITHUB_TOKEN` is preferred when both `GITHUB_TOKEN` and `BUNDLESIZE_GITHUB_TOKEN` are present (as it is more specific and allows having the other token for various other checks). The fact that `GITHUB_TOKEN` is checked as a fallback is documented.
**or**
Only `BUNDLESIZE_GITHUB_TOKEN` is considered.

**Please mention other relevant information.**
- node v8.12.0
- npm v6.4.1
- bundlesize v0.17.0
- CircleCI

**Comment by ahayes91** [comment]
Hey folks! I just came across this behaviour, where `bundlesize` was reporting a failure because one of our engineers had a `GITHUB_TOKEN` attribute set for functionality not intended for `bundlesize`.

I would be in favour of the `Only BUNDLESIZE_GITHUB_TOKEN is considered.` solution instead, to keep this bundlesize github capability very strictly scoped only to env attributes that are intended for the project. Wondering what you folks think, I can raise a new issue?

**Comment by siddharthkp** [comment]
@ahayes91 Makes sense, Does https://github.com/siddharthkp/bundlesize2 solve this for you, it uses an installation instead.

**Comment by ahayes91** [comment]
> [@ahayes91](https://github.com/ahayes91) Makes sense, Does https://github.com/siddharthkp/bundlesize2 solve this for you, it uses an installation instead.

Cool, that works! Just on this part:

> Note: When this package is feature complete, it will be merged back into the original project as bundlesize@2.0.0

Any rough idea on a timeline for that? We use Renovate to keep our deps up to date so rather than moving to bundlesize2, staying on bundlesize for now and waiting for the new release would be preferable. 

And thank you!

**Comment by siddharthkp** [comment]
> We use Renovate to keep our deps up to date so rather than moving to bundlesize2, staying on bundlesize for now and waiting for the new release would be preferable.

Fair enough!

I don't have a timeline. I'm working on bundlesize2 again to make it feature complete so that I can promote it. 

At the same time, I wrote that README 4 years ago before going completely cold on the project. So i'd not recommend holding on too long 😅
