### ISSUE TITLE
Codesponsor link at bottom of report broken

### ISSUE THREAD

**Issue by zaccolley** [siddharthkp/bundlesize#277]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

<img width="765" alt="screenshot 2019-02-13 at 12 16 53" src="https://user-images.githubusercontent.com/2591901/52711307-669b7580-2f89-11e9-81eb-331a471aa479.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

Go to a report page and scroll to the bottom

**What is the expected behavior?**

Should show an image and link to something? I think codesponsor is now 'codefund' https://codefund.io/ - Oh haha and I just read the end of this template and it mentions opencollective. So maybe it should be updated to that?

**Comment by siddharthkp** [comment]
Removed the text in https://github.com/siddharthkp/bundlesize/commit/7bced6e6d8279e632fe7b3826bc20263093e1cbd#diff-c4b5d4a975caa9594c8f2232afd745dd, forgot to close this issue
