### ISSUE TITLE
PR Status check hangs on "Pending"

### ISSUE THREAD

**Issue by tpbowden** [siddharthkp/bundlesize#280]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Pull request status reporting occasionally gets stuck in the `Pending` status

![image](https://user-images.githubusercontent.com/1159553/53091968-5ea08000-350b-11e9-91b9-df141bb655f5.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

The bundlesize status should be reported after calculating

**Please mention other relevant information.**
- node version N/A
- npm version N/A
- Operating system N/A 
- bundlesize version N/A
- CI you are using CircleCI

**Comment by siddharthkp** [comment]
Hey! Is the PR public, can you give me the link?

**Comment by tpbowden** [comment]
Hey, I'm afraid not it's on a private repo. Is there any other info I can provide?

**Comment by siddharthkp** [comment]
There must be some place where if failed in the CI logs.

It sets the pending status first and then updates it when the checks are completed.

**Comment by tpbowden** [comment]
I don't recall seeing any error logs on CI - I'll make sure and take a closer look at the output next time it happens.

**Comment by tpbowden** [comment]
@siddharthkp It has just happened again for us and there are 100% no error logs from the `bundlesize` command

**Comment by siddharthkp** [comment]
It's difficult to say what's up without debugging 😢 

Can you add me as a temporary collaborator ?

**Comment by sdwvit** [comment]
+1 same here, deploys do not work because status is pending.

**Comment by mpgon** [comment]
Same here, running on CircleCI. Seems to happens seldom and randomly. The job passes successfully without errors (https://imgur.com/a/Gzc4iOo), so I'm guessing the problem is on the service side.

**Comment by Haroenv** [comment]
Note that it seems like GitHub was partially down yesterday & today (I've been having error 500s here and there), so that is likely related

**Comment by mpgon** [comment]
I've been experiencing this intermittently for over a month

**Comment by siddharthkp** [comment]
Hi 👋 

There are multiple reasons why this can happen, definitely needs some work.

Make sure you add your 👍 to the theme on v1 roadmap: https://github.com/siddharthkp/bundlesize/issues/306#issuecomment-494732986
