### ISSUE TITLE
Mind to add basic tests?

### ISSUE THREAD

**Issue by limonte** [siddharthkp/bundlesize#289]
If would be nice to have some basic tests to check that fundamental things like the correct exit code are not broken: 

![image](https://user-images.githubusercontent.com/6059356/54859006-2d38f100-4d11-11e9-9f0f-3839a62ccf2d.png)

The golden rule of software development: if it's not tested, it's broken.

**Comment by siddharthkp** [comment]
thanks, you're not wrong 😗

**Comment by limonte** [comment]
> thanks, you're not wrong

Thanks, I know that :) Will you take some actions on this? I mean, `bundlesize` is broken and basically useless in CI (https://github.com/siddharthkp/bundlesize/issues/188#issuecomment-475818611) and the only way to fix it and prevent such issues in future is adding tests.

**Comment by limonte** [comment]
If you need some additional info on the issue, let me know, but I think you can get everything you need for debugging from https://travis-ci.org/kenwheeler/cash/builds/510054291

**Comment by siddharthkp** [comment]
> Will you take some actions on this

yes

**Comment by limonte** [comment]
Closing this issue, since tests were added in #318

Thank you @siddharthkp!
