### ISSUE TITLE
chore: Update brotli-size version

### ISSUE THREAD

**Issue by orisano** [siddharthkp/bundlesize#294]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`npm install` failed why tar has a vulnerability.

**If the current behavior is a bug, please provide the steps to reproduce.**
`npm install`

**What is the expected behavior?**
success.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information.**
- node version
- npm version
- Operating system
- bundlesize version
- CI you are using

**Comment by rpellerin** [comment]
Also, `brotli-size@0.0.1` depends on `iltorb": "^1.0.9"`, which is not compatible with NodeJS 12.
