### ISSUE TITLE
vulnerable dependency (high severity)

### ISSUE THREAD

**Issue by limonte** [siddharthkp/bundlesize#298]
![image](https://user-images.githubusercontent.com/6059356/56861301-47b55880-69a8-11e9-98e0-3255d87ea1ca.png)

![image](https://user-images.githubusercontent.com/6059356/56861310-54d24780-69a8-11e9-999a-6e439e356cae.png)

**Comment by siddharthkp** [comment]
Just published 0.17.2 with security patches
