### ISSUE TITLE
Issue with 404s and repeat requests?

### ISSUE THREAD

**Issue by kentcdodds** [siddharthkp/bundlesize#30]
See [this build](https://travis-ci.org/paypal/glamorous/builds/250103307), I'm unsure what's up...

**Comment by siddharthkp** [comment]
I think I've seen this before. Your token is not a valid one. Are you sure the token you're using has access to the `paypal` org?

**Comment by kentcdodds** [comment]
Ah, you know what, it might not... I'll have to look into that. Thanks!

**Comment by Furizaa** [comment]
I came across this too. In fact my Circle build kinda DDOS'ed the API for a hour. I didn't found the culprit exactly but I've added a test for this case that passes. So my hope is that the refactoring I did for the tests caught this by accident. 

https://github.com/siddharthkp/bundlesize/pull/20/files#diff-56b8b9382242b82de0cad2cd9a03fc0dR82

**Comment by kentcdodds** [comment]
We've authorized bundlesize with PayPal:

<img width="1012" alt="screen shot 2017-07-06 at 11 22 42 am" src="https://user-images.githubusercontent.com/1500684/27928368-2704112c-624c-11e7-939c-9b4d209eed17.png">

But it's still [not working](https://travis-ci.org/paypal/glamorous/builds/250866933) (appears to be the same issue as before). I think there are two issues here that should be dealt with:

1. Handle the failure case better, rather than hitting the API over and over again until you hit the rate limiter.
2. Figure out why authentication is failing despite being authorized...

I don't really have any ideas I'm afraid :-(

**Comment by siddharthkp** [comment]
Reopening the issue. I'll debug this with a dummy private repo

**Comment by kentcdodds** [comment]
That's very kind of you. Thanks!

**Comment by siddharthkp** [comment]
Hey, I've added a debug mode in `0.9.0`.

Can you try that out and with `bundlesize --debug` and send me the logs 😄

**Comment by kentcdodds** [comment]
Boom, it's magically working now! https://travis-ci.org/paypal/glamorous/builds/253438758

**Comment by kentcdodds** [comment]
Thanks a ton for all the hard work you put into this :smile:

**Comment by siddharthkp** [comment]
lolwut! 

might be some other bug that I ended up fixing 😀

**Comment by kentcdodds** [comment]
It appears to be broken again: https://travis-ci.org/paypal/glamorous/builds/257111820

**Comment by kentcdodds** [comment]
Here's the `--debug` output:

```
WARN  cli config: undefined 

WARN  package json config: [
 {
   "path": "dist/glamorous.umd.tiny.min.js",
   "threshold": "3kB"
 },
 {
   "path": "dist/glamorous.es.tiny.js",
   "threshold": "5kB"
 },
 {
   "path": "dist/glamorous.cjs.tiny.js",
   "threshold": "5kB"
 }
] 

WARN  selected config: [
 {
   "path": "dist/glamorous.umd.tiny.min.js",
   "threshold": "3kB"
 },
 {
   "path": "dist/glamorous.es.tiny.js",
   "threshold": "5kB"
 },
 {
   "path": "dist/glamorous.cjs.tiny.js",
   "threshold": "5kB"
 }
] 

WARN  files: [
 {
   "maxSize": 3072,
   "path": "dist/glamorous.umd.tiny.min.js",
   "size": 2333
 },
 {
   "maxSize": 5120,
   "path": "dist/glamorous.es.tiny.js",
   "size": 4905
 },
 {
   "maxSize": 5120,
   "path": "dist/glamorous.cjs.tiny.js",
   "size": 4988
 }
] 

WARN  token exists: true 

WARN  repo: "paypal/glamorous" 

WARN  sha: "284e20c01f8c9350fc10dcfe7582864b445c5dde" 

WARN  api enabled: true 

WARN  fetching values: "..." 

Unhandled Promise: 
Promise {
 <rejected> { status: 401,
 error: 
  { message: 'Bad credentials',
    documentation_url: 'https://developer.github.com/v3' } } }
{ status: 401,
 error: 
  { message: 'Bad credentials',
    documentation_url: 'https://developer.github.com/v3' } }
Unhandled Promise: 
Promise {
 <rejected> { status: 401,
 error: 
  { message: 'Bad credentials',
    documentation_url: 'https://developer.github.com/v3' } } }
{ status: 401,
 error: 
  { message: 'Bad credentials',
    documentation_url: 'https://developer.github.com/v3' } }
Unhandled Promise: 
Promise {
... forever and ever
```

2 things:

1. I'm not sure what's up with the Bad credentials stuff :-(
2. If a failure happens, could we please not retry a million times and just give up after 3 or something?

**Comment by siddharthkp** [comment]
> If a failure happens, could we please not retry a million times and just give up after 3 or something?

Definitely. Will fix that.

> I'm not sure what's up with the Bad credentials stuff :-(

Are you, by any change, on github enterprise?

**Comment by kentcdodds** [comment]
> Definitely. Will fix that.

Great! thanks!

> Are you, by any change, on github enterprise?

Not for this repo.

**Comment by siddharthkp** [comment]
`bundlesize@0.13.2` fixes the recursive failure.

As for the token issue, bundlesize uses [github-build](github.com/siddharthkp/github-build) underneath.

Here's a test case that you can run with your {repo, sha, token} to check if it works: [runkit/siddharthkp/5977214](https://runkit.com/siddharthkp/5977214f2fb87a001263ed35)

**Comment by kentcdodds** [comment]
Sadly, I don't have admin rights on the PayPal org and it's tough to get a key. So it's unlikely that I'll pursue this much further for glamorous. Sorry :-(

**Comment by siddharthkp** [comment]
@kentcdodds okay, I understand 😔 

I'm pretty sure that the token has expired/is invalid. Let me know if you change your mind later 😄

**Comment by siddharthkp** [comment]
Closing this issue for now.
