### ISSUE TITLE
`threshold null gzip` error

### ISSUE THREAD

**Issue by leggsimon** [siddharthkp/bundlesize#32]
I've noticed that the docs use `maxSize` in the config, since the tagged release hasn't happened yet to change the internals to use `maxSize` it uses `threshold` instead. Giving an error like this
```
./dist/assets/es5.min.js: 65.19kB > threshold null gzip
```
To fix change the property in your `package.json` to from `maxSize` to `threshold`.

Just popping this here for anyone getting the error.

**Comment by reznord** [comment]
@leggsimon you can still use threshold value too !! In the `README`, it has been removed. 

Backward compatibility is still there.

**Comment by siddharthkp** [comment]
@reznord, this is my bad.

I haven't published your change to npm

**Comment by leggsimon** [comment]
In the `v0.6.1` tag it hasn't got backwards compat. https://github.com/siddharthkp/bundlesize/blob/v0.6.1/src/files.js#L13

**Comment by leggsimon** [comment]
Looks like a good project though! Keen to see where it goes and maybe help out along the way.

Also, obviously feel free to close this issue once the change is published.

**Comment by reznord** [comment]
@siddharthkp I've fixed this after you released `0.6.1`. So, no worries :) 

I think bundlesize can get a next version, since there are a few fixes :D

**Comment by siddharthkp** [comment]
For now, I'm undoing your changes in the README. 

Will push a new version soon.

**Comment by siddharthkp** [comment]
@leggsimon Sorry for that! You can use `threshold` for now 😄

**Comment by siddharthkp** [comment]
> I think bundlesize can get a next version, since there are a few fixes :D

Yeah, there are some that I haven't tested yet. Soon, I promise!
