### ISSUE TITLE
Support of Asset Map in addition to the Path Parameters to Define the list of Files

### ISSUE THREAD

**Issue by zakuru** [siddharthkp/bundlesize#333]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Bundle Size supports only path parameter. Would be great to be able to provide the asset map file instead so that we can detect change in size per entry point for a better granularity.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information.**
- node version
- npm version
- Operating system
- bundlesize version
- CI you are using

**Comment by siddharthkp** [comment]
That sounds like a really good idea. I think the best way to implement would be as a "input" plugin.

When this plugin is used, it feeds an array of file paths instead of reading from the config.

(bundlesize doesn't support plugins yet, but it's on the roadmap)

What do you think?

**Comment by zelmarou** [comment]
Hey thanks so much for the feedback.
I was thinking about implanting an additional parameter that would override the path parameter. What would be an input plugin ? I'm just not completely sure I understand the concept.

**Comment by zelmarou** [comment]
@siddharthkp let me know what you think

**Comment by siddharthkp** [comment]
> I was thinking about implementing an additional parameter that would override the path parameter. 

I'm a little resistant to adding more flags.

> What would be an input plugin ? I'm just not completely sure I understand the concept.

It's not implemented yet so I don't blame you 😋 I'm working on a plugin system for bundlesize where you should be able to introduce code that's run before (input) or after (output) the main script in bundlesize. I'll make sure I document it properly once before I merge it 👍
