### ISSUE TITLE
GZIP Sizes

### ISSUE THREAD

**Issue by tizmagik** [siddharthkp/bundlesize#36]
First, thanks for this, this is great! ✨ 

Curious if you'd be open to a PR that would allow for reporting on GZIP sizes instead of/in to just the Disk Size kb? Perhaps using something like [gzip-size](https://github.com/sindresorhus/gzip-size)

**Comment by siddharthkp** [comment]
Fun thing, bundle size already uses gzip-size.

I see that the docs are not explicit about that, I'll add that

**Comment by tizmagik** [comment]
Oh, sweet. Thanks!
