### ISSUE TITLE
Feature: Support for Buddy CI

### ISSUE THREAD

**Issue by penx** [siddharthkp/bundlesize#361]
I think support for [Buddy CI](https://buddy.works) could be added reasonably easily by looking for these env variables:

(note I don't think Buddy has CI=true by default, but does have BUDDY=true)

if process.env.BUDDY=true
- CI_REPO_NAME=BUDDY_PROJECT_NAME or BUDDY_PROJECT_NAME_ID or extract from BUDDY_REPO_SLUG
- CI_REPO_OWNER=BUDDY_WORKSPACE_DOMAIN or extract from BUDDY_REPO_SLUG
- CI_COMMIT_SHA=BUDDY_EXECUTION_REVISION
- CI_COMMIT_MESSAGE=BUDDY_EXECUTION_REVISION_MESSAGE

https://buddy.works/docs/pipelines/environment-variables

**Comment by siddharthkp** [comment]
if you want to implement this, his is the place to add it to: https://github.com/siddharthkp/ci-env

**Comment by penx** [comment]
@siddharthkp cool, done! https://github.com/siddharthkp/ci-env/pull/37

**Comment by siddharthkp** [comment]
Hey! Merged the PR from ci-env and updated the dependency for bundlesize2

https://github.com/siddharthkp/bundlesize2 which solves a bunch of issues in bundlesize and will eventually be published as 1.0.0

**Comment by penx** [comment]
Cheers. Think I need to fix something with the buddy env vars specifically repo owner isn’t guaranteed. Will take a look shortly

**Comment by penx** [comment]
Gonna extract it from BUDDY_REPO_SLUG instead I think
