### ISSUE TITLE
Add support for node versions 12.x and above

### ISSUE THREAD

**Issue by vinodh-kumar-1711** [siddharthkp/bundlesize#374]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The build is failing if we use node versions greater than v10.16.0 because of the iltorb package which is an internal dependency of brotli-size@0.1.0.

**What is the expected behavior?**
It should work properly in node versions 12.x and above

**If this is a feature request, what is motivation or use case for changing the behavior?**
Unable to upgrade the node versions because of the iltorb dependency.

The iltorb module is deprecated in favour of zlib (https://www.npmjs.com/package/iltorb). Upgrading the brotli-size package to v4.0.0 solves this issue as it no longer depends on the iltorb package.

**Please mention other relevant information.**
- node version 12.16.3
- npm version  6.14.4
- Operating system Mac OS - Monterey
- bundlesize version 0.18.1
- CI you are using Jenkins

Log:
node_modules/brotli-size/node_modules/iltorb

/src/dec/[stream_decode.cc](http://stream_decode.cc/):14:72: error: no matching member function for call to 'ToObject'
    Local<Object> dictionary = Nan::Get(params, key).ToLocalChecked()→ToObject();

**Comment by igorfv** [comment]
I'm using v16.16.0 and it's working fine

**Comment by vinodh-kumar-1711** [comment]
Oh yeah you are right. We had another direct dependency to iltorb package in our repo which was causing the issue. In our yarn.lock file I found the reference for the iltorb package in the bundlesize package as well so I assumed this is also causing the issue and reported it. Sorry my bad, will close it. Thanks @igorfv
