### ISSUE TITLE
Test for the sum of all chunks sizes

### ISSUE THREAD

**Issue by igorfv** [siddharthkp/bundlesize#376]
**Do you want to request a *feature* or report a *bug*?**
Feature.
Make it possible to check for the total size for a group of files instead of individual changes.

**What is the current behavior?**
The size is limited for each individual chunk.
```JSON
"bundlesize": [
    {
      "path": "./build/static/**/*.js",
      "maxSize": "950 kb"
    }
  ]
```
 Outputs
```
PASS  ./build/static/js/385.5c60ec09.chunk.js: 13.96KB < maxSize 950KB (gzip) 
PASS  ./build/static/js/872.5ecb0094.chunk.js: 15.1KB < maxSize 950KB (gzip) 
PASS  ./build/static/js/main.9bf15a44.js: 39.88KB < maxSize 950KB (gzip) 
PASS  ./build/static/js/vendors.51d60d15.js: 928.38KB < maxSize 950KB (gzip) 
```

**What is the expected behavior?**
Given a configuration, limit the size for the sum of all files.

The proposed solution: adding a mode prop (the default behavior is "single")
```JSON
"bundlesize": [
    {
      "path": "./build/static/**/*.js",
      "maxSize": "1 mb",
      "mode": "group"
    }
  ]
```
   Outputs
```
FAIL 1008.63kb > maxSize 950KB (gzip) 
 > ./build/static/js/385.5c60ec09.chunk.js: 13.96KB
 > ./build/static/js/872.5ecb0094.chunk.js: 15.1KB
 > ./build/static/js/main.9bf15a44.js: 39.88KB
 > ./build/static/js/vendors.51d60d15.js: 928.38KB
```

**If this is a feature request, what is the motivation or use case for changing the behavior?**
Being able to control the total app size instead of individual chunks

**Comment by siddharthkp** [comment]
This has come up in the past: https://github.com/siddharthkp/bundlesize/issues/205 and something that I'd like to shy away from
