### ISSUE TITLE
Notify on bundle size *decrease*?

### ISSUE THREAD

**Issue by tizmagik** [siddharthkp/bundlesize#38]
Let's say bundle.js starts at 50KB, so we set threshold to 55KB. Then, some incredible PR comes in and reduces the bundle to 40KB -- that's great! 😃  But, now our threshold is still at 55KB 😢  

Ideally we'd like to know about this and be reminded to update the bundlesize threshold to something better, like 45KB, for example.

Thoughts?

**Comment by siddharthkp** [comment]
`bundlesize` does inform you about decrease in size as well. You would see something like this on your terminal/github status:

` PASS  ./dist.js: 40kB < threshold 55kB gzip (10kB smaller than master, good job!) `

That should be in indicator to improve your threshold.

**Comment by tizmagik** [comment]
Oh awesome! Sorry, was just looking at the [comment block here](https://github.com/siddharthkp/bundlesize/blob/master/src/reporter.js#L18-L22) and didn't actually read through the conditional logic. This is great, thanks!
