### ISSUE TITLE
Axios dependency has vulnerability

### ISSUE THREAD

**Issue by bj00rn** [siddharthkp/bundlesize#380]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

![image](https://github.com/siddharthkp/bundlesize/assets/10961167/74d3ae3a-e57e-49f0-8a38-261da4ec4379)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information.**
- node version: 10x
- Operating system
- bundlesize version: 0.18.1

**Comment by siddharthkp** [comment]
PR welcome!

**Comment by bj00rn** [comment]
@siddharthkp lot's of open PRs here though, is this being maintained?

also dependencybot will do a good job at keeping up with these things, maybe enable it?

**Comment by siddharthkp** [comment]
> lot's of open PRs here though, is this being maintained?

sometimes, for moments like these

**Comment by bj00rn** [comment]
did https://github.com/siddharthkp/bundlesize/pull/381

tests are failing locally though, no idea why, does not seem related to axios

also I noticed [github-builder](https://github.com/bj00rn/bundlesize/blob/585d291df61c984b6d61a5f18a9ce84930f0c2d7/package.json#L45C5-L45C5) is in dependencies and depends on axios. Needs fixing or move to devDependencies if not used

**Comment by poojagunturu96** [comment]
I submitted a PR for this as well #382, based off of @bj00rn['s PR](https://github.com/siddharthkp/bundlesize/pull/381). I also updated `github-build` as it was also dependent on `axios`.

**Comment by ruZZintl** [comment]
> > lot's of open PRs here though, is this being maintained?
> 
> sometimes, for moments like these

Please update these dependencies due to vulnerabilities. Thanks.

**Comment by palashmon** [comment]
Fixed in PR #382
