### ISSUE TITLE
Support webpack filenames that include chunkhash

### ISSUE THREAD

**Issue by kumar303** [siddharthkp/bundlesize#39]
We output our asset files using webpack with a filename like `[name]-[chunkhash].js`; this looks like `amo-581f1494a4fa6d00f237.js`. Is there a way to use bundlesize to track this? I couldn't think of a way to do this from your README.

**Comment by tizmagik** [comment]
We were able to do this in our project by setting the filename like so: `amo-*.js` -- seemed to work.

cc, @montmanu

**Comment by kumar303** [comment]
ok, thanks. That started working but we also have locale bundles (e.g. `amo-i18n-fr-c040d4156308916c9f3c.js`) that I'd like to track separately. I guess I can get creative with the prefixes to make it work.

**Comment by montmanu** [comment]
could also get creative with the glob pattern.. see https://github.com/isaacs/node-glob for the various pattern options..

**Comment by ankibalyan** [comment]
@siddharthkp I'm trying something on this, will get a PR.

**Comment by siddharthkp** [comment]
@montmanu is right, `bundlesize` already uses [glob](https://github.com/isaacs/node-glob), so you can give filenames like `name-*.js`. It will pick each file separately.

@kumar303 In your case, you can use `amo-i18n-fr-*.js` and `amo-i18n-in-*.js` as 2 different blocks as well if you want different sizes for them, or just merge them into one with `amo-18n-*.js` which will give you:

```
 PASS  ./amo-18n-fr-cad4f3444.js: 189B < threshold 600B gzip
 PASS  ./amo-18n-pt-oo4f5345.js: 189B < threshold 600B gzip
```

**Comment by ankibalyan** [comment]
@siddharthkp I've update README.md  in PR just to be clear for one to configure multiple and grouped paths. 

you can add that for ease :)

**Comment by siddharthkp** [comment]
@kumar303 I'll close this issue then. Feel free to comment (and reopen) if it doesn't work for you.

**Comment by kumar303** [comment]
Thanks! The README example you added is exactly what I was missing.
