### ISSUE TITLE
Server implementation of `api.set` seems to ignore multiple files

### ISSUE THREAD

**Issue by montmanu** [siddharthkp/bundlesize#47]
we currently include 4 separate file blocks in our `bundlesize` config.. when [`api.set(values)`](https://github.com/siddharthkp/bundlesize/blob/master/src/reporter.js#L55) is executed with multiple files, only the first seems to be persisted.. our response for `https://bundlesize-store-iothfynuyu.now.sh/values?repo=${environment.repo}&token=${environment.token}` includes only the first item of that `values` array..

**Comment by siddharthkp** [comment]
Yes, you're right.

That was intentional at the time, the message would not look nice. I should fix that.

**Comment by siddharthkp** [comment]
@montmanu Please upgrade bundlesize to latest version 😄  This issue is fixed.

**Comment by montmanu** [comment]
Thanks @siddharthkp!
