### ISSUE TITLE
Guide for the contributors

### ISSUE THREAD

**Issue by echo304** [siddharthkp/bundlesize#48]
I really want to contribute to this project and have an idea to improve some feature, because my team in Tapjoy started to use it for small project.
But I'm not sure how to build and test on my local machine. So it would be super helpful if you add some guide for the contributors.
And I appreciate for your effort!

**Comment by siddharthkp** [comment]
Yes, will do! 

I'm a little busy week. Will add it early next week

**Comment by siddharthkp** [comment]
@echo304 There you go: https://github.com/siddharthkp/bundlesize/blob/master/CONTRIBUTING.md

Thanks for pointing this out 😄
