### ISSUE TITLE
Globbing for filename

### ISSUE THREAD

**Issue by mmahalwy** [siddharthkp/bundlesize#53]
We tend to have a hash generated with filename, thus:
`main-SOME_RANDOM_HASH.js`

**Comment by siddharthkp** [comment]
Hey, `bundlesize` already supports that 😄 

Just added that to the README: https://github.com/siddharthkp/bundlesize/blob/master/README.md#configuration

**Comment by siddharthkp** [comment]
Closing this issue. Feel free to reply back if this doesn't solve your problem.

**Comment by mmahalwy** [comment]
Baller! Thanks a bunch :)

**Comment by pun4drunk** [comment]
What about master size comparisons? Using generated bundle names results each file not having an older version to compare

**Comment by agoldis** [comment]
@siddharthkp echoing @pun4drunk question - in my project (and usually) we have bundles generated with a hash suffix, so every build generates a new filename - when this awesome tool compares to the previous build, it is always `(-null)`

![screen shot 2018-08-28 at 12 48 50 pm](https://user-images.githubusercontent.com/1637928/44746967-c62bc480-aac0-11e8-931e-edde62fb3a1f.png)

May be it is supported already... can't figure out how to use :(

**Comment by mmahalwy** [comment]
Same here^
