### ISSUE TITLE
Show test result for multiple files

### ISSUE THREAD

**Issue by echo304** [siddharthkp/bundlesize#55]
I use bundlesize for my team's project and add multiple files for the testing.
Unfortunately we got simple log not the result for whole multiple files.
<img width="573" alt="2017-07-11 9 17 44" src="https://user-images.githubusercontent.com/16456651/28067955-6e437ca4-667e-11e7-9415-b3329ba0e96a.png">

How about make it support for multiple file logging?

**Comment by siddharthkp** [comment]
Yeah, if there are multiple files that changed, bundlesize falls back to a generic message.

These are the possible solutions in my head:

- Show multiple status messages - one for each file: Could get out of hand pretty fast for applications.
- Link to the CI build logs: Not sure if I can get the exact line number from all the supported CI environments
- Store this data in firebase and build a UI on top of that: A lot more effort, but, this is what I'm leaning towards

Ideas?

**Comment by echo304** [comment]
I agreed on option 3, too and want to tackle it. But It seems that I'm not able to work and test on API part(`./store/**`) of the source code.

**Comment by siddharthkp** [comment]
@echo304 Yeah, you'll have to do a parallel setup.

This is something that I am going to pick up real soon 😎

**Comment by rickhanlonii** [comment]
@siddharthkp for v1 you could probably store the files/sizes in the URL and create a simple page that displays the per-file info based on the URL, then you wouldn't need to upload to firebase with every build

i.e. POST to GitHub:

```js
{
  "state": "failure",
  "target_url": "https://bundlesize-store.now.sh/status?app.js=1.1MB,1MB&vendor.js=900kB,1MB",
  "description": "Uh Oh! 1 file over max bundle size",
  "context": "bundlesize"
}
```

Query params are `filenname=expected,actual`. I think that gives you all the data you need to show the report. Of course, you're limited by URL length in the number of files you can show (but this you can solve by only showing failed files if you're over the limit, and showing a generic error if even the failed files are too many)

**Comment by siddharthkp** [comment]
That's a great idea. Can probably encode the data to fit in more within a url. 

Although, I do my eyes on building a time series graph as well, so storing the data in fire base will be the first step towards that.

**Comment by siddharthkp** [comment]
@rickhanlonii whoops, I was completely wrong. Time series data only matters on `master`.

So, I'm going to go with your approach for build details. Thanks for the idea 💙

**Comment by rickhanlonii** [comment]
Yeah that makes sense, no sweat!

**Comment by siddharthkp** [comment]
@echo304 @rickhanlonii Great news, just launched details page for multiple files

<img width="1000" alt="screen shot 2017-07-16 at 4 08 53 am" src="https://user-images.githubusercontent.com/1863771/28243103-9043fa7a-69dc-11e7-985d-d81b9464dbba.png">

Upgrade to bundlesize@0.12.0 😄

**Comment by rickhanlonii** [comment]
Woah! Very cool!!
