### ISSUE TITLE
bundle-buddy integration

### ISSUE THREAD

**Issue by reznord** [siddharthkp/bundlesize#56]
It would be great to add [bundle-buddy](https://github.com/samccone/bundle-buddy) to bundlesize to give more insights into the bundle (which all packages are eating more and which package are using same resources.

@siddharthkp any suggestions?

**Comment by siddharthkp** [comment]
Super useful for https://github.com/siddharthkp/bundlesize/issues/27

Thanks for pointing this out!

**Comment by siddharthkp** [comment]
I'm not sure if this should be part of the core or as a plugin 🤔

**Comment by reznord** [comment]
making this a part of the code doesn't harm though !! Since everyone may be interested in seeing the results :D

**Comment by siddharthkp** [comment]
Maintaining this agenda in https://github.com/siddharthkp/bundlesize/issues/27
