### ISSUE TITLE
size badge?

### ISSUE THREAD

**Issue by FezVrasta** [siddharthkp/bundlesize#7]
I know there are already services that provide badges with the bundle size, but I think there's market for a dedicated "bundlesize" badge which may provide more informations compared to the classic ones.

For instance, it would be super cool to have the badge link to a page that keeps track of the size variations during time.

**Comment by siddharthkp** [comment]
> For instance, it would be super cool to have the badge link to a page that keeps track of the size variations during time.

I love it.

One tiny question though, the badge should show the **published** version's size, not the one in the master branch.

Any idea on how to handle that? A postpublish hook might work 🤔

**Comment by FezVrasta** [comment]
On my project page I make the badge read the size from unpkg.com, but I see how this could not be an ideal solution.

**Comment by siddharthkp** [comment]
Let me think about it, this is definitely something that is useful.

**Comment by bfred-it** [comment]
If the file is in the repo, you can already use this (with a gzip option as well): https://github.com/exogen/badge-matrix#sizesourcepath

Example:

![](https://badges.herokuapp.com/size/github/bfred-it/iphone-inline-video/master/dist/iphone-inline-video.min.js?gzip=true&label=gzipped%20size)

```
![](https://badges.herokuapp.com/size/github/bfred-it/iphone-inline-video/master/dist/iphone-inline-video.min.js?gzip=true&label=gzipped%20size)
```

**Comment by nitish24p** [comment]
Preact has a gzip size badge. Wondering if aomething similar can be used..

**Comment by axe312ger** [comment]
Preact uses http://badgesize.io/ which ends up in an empty page. But the service looks great!
```
[![gzip bundle size](http://img.badgesize.io/https://unpkg.com/contentful-management/dist/contentful-management.min.js?compression=gzip
)](https://unpkg.com/contentful-management/dist/contentful-management.min.js)
```
turns into
[![gzip bundle size](http://img.badgesize.io/https://unpkg.com/contentful-management/dist/contentful-management.min.js?compression=gzip
)](https://unpkg.com/contentful-management/dist/contentful-management.min.js)

:)

Watching here, since I prefer a solution from `bundlesize` :)

**Comment by siddharthkp** [comment]
@axe312ger @nitish24p The thing which makes unpkg a better source is that it pulls the file from the npm registry, bundlesize only knows what's on github, now what's published

This can be solved with a postpublish hook which tells bundlesize the sha for the published version. I imagine the command to be something like this:

```json
"scripts": {
  "test": "jest && bundlesize",
  "prepublish": "npm run build && npm test",
  "postpublish": "bundlesize tag published"
}
```

**Comment by sreetamdas** [comment]
Any updates here?

**Comment by siddharthkp** [comment]
@sreetamdas Not really, I'm not sure if this should be implemented in bundlesize 🤔

**Comment by palashmon** [comment]
Closing this issue for now because it has not had recent activity. Thank you for your contributions.
