### ISSUE TITLE
Why do you need access to my private repositories?

### ISSUE THREAD

**Issue by axe312ger** [siddharthkp/bundlesize#71]
Hey there,

great tool, I'd love to but I can not use it:

My employer has also private, non-public code in the GitHub organization. I would love to use this tool's GitHub integration to display the bundle size nicely with every open source PR we get.

But, I am not allowed to activate the integration, since it ask's for full private repository access.

Why do you need that access by default? Is there a way to have a bundle-size which is only integrating with public repositories?

I am pretty sure most use-case here are opensource projects which will be public anyways.

Thank you very much,
Benedikt

**Comment by siddharthkp** [comment]
Hey Benedikt, thanks for the well detailed out question.

1.
> I am not allowed to activate the integration, since it ask's for full private repository access.

I think that's a misunderstanding, bundlesize does not need _full private repository access_, it only asks permissions for `repo:status`

From [github docs](https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-scopes-for-oauth-apps/), this is what it means: 

> Grants read/write access to public and private repository commit statuses. This scope is only necessary to grant other users or services access to private repository commit statuses without granting access to the code.

2.

> Why do you need that access by default?

bundlesize adds a build status on your commit/pull request, for that it needs `repo:status` access. It's the recommended way of using bundlesize but completely optional.

3. 
> Is there a way to have a bundle-size which is only integrating with public repositories?

Unfortunately, GitHub does not provide that level of fine grained access control. 

4.
> I am pretty sure most use-case here are opensource projects which will be public anyways

Nope, there are about a dozen folks using it for their private applications as well 😄

I think you should show your employer the [access permission page](https://github.com/login/oauth/authorize?scope=repo%3Astatus&client_id=6756cb03a8d6528aca5a), that will convince them that I only want to set `repo:status` and not steal all your code 😅

**Comment by axe312ger** [comment]
Thank you, will discuss it with them :)

**Comment by pxlpnk** [comment]
Hey,

as the reviewer in some organizations only sees this screen:
![application_access_policy](https://user-images.githubusercontent.com/164718/28276138-4d8ab292-6b16-11e7-8bf8-5e30fb7effaf.png)


It could make sense to use the bit of text to explain (or have a link to an explanation) the required permissions. I have seen circle and others do that.

This would allow the reviewer to get a better understanding of the actually used scope. It is a bit unfortunate that GitHub hides those details.

**Comment by siddharthkp** [comment]
Ah, I haven't seen this screen. Thanks @pxlpnk!

Updated the description on github oauth settings

```
Keep your bundle size in check
   
bundlesize needs access to public and private repository commit statuses.

Granting access will not give access to the code or settings.
```

**Comment by pxlpnk** [comment]
Thank you 🙇

**Comment by axe312ger** [comment]
Thanks <3
