### ISSUE TITLE
Long bundle path causes truncation of text in GitHub UI

### ISSUE THREAD

**Issue by jazlalli** [siddharthkp/bundlesize#72]
As you can see from the screenshot below

![screen shot 2017-07-19 at 18 11 50](https://user-images.githubusercontent.com/1867746/28412414-11c9aa9c-6d3c-11e7-9d64-3d02df010843.png)

Perhaps only showing that last directory and the filename, prefixed with `...` would be better, as the most useful information follows that. The full path could be shown when hovering over the summary.

If you have a solution in mind, I'd be happy to try and make the change for you. I'm guessing doing some path manipulation [here](https://github.com/siddharthkp/bundlesize/blob/master/src/reporter.js#L15-L17) would do it?

**Comment by siddharthkp** [comment]
Sounds good@

**Comment by palashmon** [comment]
I am not working on this case yet, but I just wanted to discuss some test case scenarios and gets inputs from other also. This might be helpful for any other contributor who wants to work on it in future.

  - ### Best case scenario
     When file name is short like:
     ```
     ./dist.js
     ```
     In this case no truncation of text is needed.

  - ### 2nd scenario
     When file path is long like:
     ```
     ./lighthouse-extension/dist/scripts/lighthouse-background.js
     ```
     In this case, I think we can truncate it to like `~/lighthouse-background.js`.
     What do you think?

  - ### 3rd scenario
     When file name is long (more than 35 chars) like:
     ```
     ./lighthouse-background-long-filename.js
     ```
     In this case, I think we can truncate it to something like `~/light...name.js`.
     What do you think?

What other test case scenarios we have?

**Comment by siddharthkp** [comment]
I like all of those solutions!

I'd also like to add the case of multiple files in possibly different folders.

**Comment by siddharthkp** [comment]
Another thing I'll throw into the mix is: should we do this in the CLI or on the store/details page.

Doing it in the CLI is a more effective use of URL length, but doing on the details page gives us the flexibility of deploying whenever we want even with breaking changes.

**Comment by siddharthkp** [comment]
Whoops, we should this conversation to https://github.com/siddharthkp/bundlesize/pull/81

**Comment by vs1682** [comment]
You mean showing the path with it's parent directory, right?
Like
`~/parent1/file1.js`
`~/parent2/file2.js`

**Comment by siddharthkp** [comment]
@vs1682 yep.

moved to #82
