### ISSUE TITLE
500 error?

### ISSUE THREAD

**Issue by FezVrasta** [siddharthkp/bundlesize#75]
https://travis-ci.org/FezVrasta/popper.js/builds/256016144#L1702

Ideas?

**Comment by siddharthkp** [comment]
Oh yeah, this issue existed in an initial version. Because you're caching `node_modules` on travis, you didn't get the upgrade.

Raised a pull request - https://github.com/FezVrasta/popper.js/pull/358

**Comment by siddharthkp** [comment]
Feel free to comment back if that doesn't fix it and I'll reopen the issue 😄

**Comment by FezVrasta** [comment]
Cool doing so it works, but I get this:

https://travis-ci.org/FezVrasta/popper.js/builds/256375041#L1536

even if I have the `github_token` set:
![image](https://user-images.githubusercontent.com/5382443/28491885-dc48d294-6ef8-11e7-83f8-966f203112ce.png)

**Comment by FezVrasta** [comment]
Nevermind, looks like you change the name of the token from `github_token` to `BUNDLESIZE_GITHUB_TOKEN`

**Comment by FezVrasta** [comment]
Me again.. I added the token with the right name and I'm still getting that warning :-(

![image](https://user-images.githubusercontent.com/5382443/28491941-c5184f04-6ef9-11e7-83cf-9600b78edde0.png)

**Comment by siddharthkp** [comment]
`github_token` should also work. It's backward compatible.

I'm out at the moment, I'll definitely check once I'm back home
