### ISSUE TITLE
Upgrade chalk to version 2.0.1

### ISSUE THREAD

**Issue by palashmon** [siddharthkp/bundlesize#89]
There is a newer version of [`chalk`](https://www.npmjs.com/package/chalk) released that this project depends on.

Please update to latest and test it out.
Regards!

**Comment by cg-cnu** [comment]
I was just looking into it and I didn't find any mention of `chalk` in `package.json`
Even the [search results](https://github.com/siddharthkp/bundlesize/search?q=chalk&type=Issues&utf8=%E2%9C%93) are showing nothing except this issue.
Am I missing something ? Let me know!

**Comment by SaraVieira** [comment]
Same here @palashmon 

<img width="647" alt="screenshot 2017-08-26 21 27 36" src="https://user-images.githubusercontent.com/1051509/29744857-42741700-8aa5-11e7-8ebc-d9da16076f39.png">

**Comment by siddharthkp** [comment]
I think I know what's up. This package uses [prettycli](https://github.com/siddharthkp/prettycli) which uses chalk!

**Comment by cg-cnu** [comment]
Then we should move this issue to prettycli ?

**Comment by reznord** [comment]
yup! [Here](https://github.com/siddharthkp/prettycli/issues/4) you go.

**Comment by palashmon** [comment]
> I think I know what's up. This package uses prettycli which uses chalk!
Yup, that was the main repo I was trying to point to actually, but added this here by mistake as prettycli is also created by you. Sorry about that. Beginner mistake.

You can close this issue now.

**Comment by siddharthkp** [comment]
Thanks for taking the time to create an ssue 🙂
