### ISSUE TITLE
[feature request] Accept piped file 

### ISSUE THREAD

**Issue by Andarist** [siddharthkp/bundlesize#90]
**Why?**
Would be super useful to have this in place so we could pipe in output of another program, i.e. one which strips down comments.

Im happy to help with implementing this, just reaching out first with the idea as suggested in CONTRIBUTING section ;)

**Comment by siddharthkp** [comment]
Hey, yep makes a lot of sense. 

What's your view on implementing a --json flag, would that be useful?

**Comment by Andarist** [comment]
Hmm, `--json` would mean "accept a piped input stream"? Imho - kinda weird, I would never guess :P

From what I udnerstand we can detect if we are in a 'piped' mode by using [`Boolean(process.stdout.isTTY) === false`](https://nodejs.org/api/tty.html).

I've looked really quickly into the source code, but changes I would make to support this:
- warn about conflicting CLI options - `files` with piped data doesnt make much sense imho
- possibly add a new option for a 'piped' mode, smth like `--name lib.min.js` (or maybe something like `--pathName` to align with what gets reported now) because in such situation we have only the file contents and it still is valuable to track size over time (we could default to `readPkgUp.sync().pkg.name` for this)
- build a little more explicit pipeline of operations, now `src/files.js` depends internally on `src/config.js`
- with more explicit pipeline I would also decouple reading files content from checking their sizes (so 'piped' mode can easily skip reading part and use only the latter)

**Comment by siddharthkp** [comment]
Oh sorry, what I meant was bundlesize can print in json format which can be consumed by other scripts.

That doesn't answer your questions about pipes, my bad.

> From what I udnerstand we can detect if we are in a 'piped' mode by using Boolean(process.stdout.isTTY) === false.

This is so cool! I did not know about this.

> possibly add a new option for a 'piped' mode, smth like --name lib.min.js (or maybe something like --pathName to align with what gets reported now) because in such situation we have only the file contents and it still is valuable to track size over time (we could default to readPkgUp.sync().pkg.name for this)

I'm not sure if that's the best approach. I think you can create another [executable](https://github.com/siddharthkp/bundlesize/blob/master/package.json#L7-L8) `bundlesize-pipe` which skips the inital files stuff and directly starts at the reporting stage.

What do you think?

**Comment by Andarist** [comment]
> Oh sorry, what I meant was bundlesize can print in json format which can be consumed by other scripts.

That would probably be useful too for other use cases!

> I'm not sure if that's the best approach. I think you can create another executable bundlesize-pipe which skips the inital files stuff and directly starts at the reporting stage.

Another executable sounds nice, no problems with conflicting options.

However I would still argue that its super useful to give a name for the piped data through option. And that decoupling reading files from the config (and all that ive described above) would be great, so those pieces could get reused in `bundlesize-pipe`.
