### ISSUE TITLE
Multiple packages can be too long to parse for GUI

### ISSUE THREAD

**Issue by jbaxleyiii** [siddharthkp/bundlesize#94]
We are moving to a lerna repo with Apollo and setup 5 filesize tests. With the current link generation, the UI fails to parse the JSON (it appears to be cut off). [Example Link](https://bundlesize-store.now.sh/build?info=%7B%22files%22%3A%5B%7B%22maxSize%22%3A1024%2C%22path%22%3A%22.%2Fpackages%2Fapollo-cache-core%2Fdist%2Findex.min.js%22%2C%22size%22%3A638%7D%2C%7B%22maxSize%22%3A5632%2C%22path%22%3A%22.%2Fpackages%2Fapollo-cache-inmemory%2Fdist%2Findex.min.js%22%2C%22size%22%3A5519%7D%2C%7B%22maxSize%22%3A11264%2C%22path%22%3A%22.%2Fpackages%2Fapollo-client%2Fdist%2Findex.min.js%22%2C%22size%22%3A10806%7D%2C%7B%22maxSize%22%3A35840%2C%22path%22%3A%22.%2Fpackages%2Fapollo-client-preset%2Fdist%2Findex.min.js%22%2C%22size%22%3A34578%7D%2C%7B%22maxSize%22%3A4608%2C%22path%22%3A%22.%2Fpackages%2Fapollo-utilities%2Fdist%2Findex.min.js%22%2C%22size%22%3A4202%7D%2C%7B%22maxSize%22%3A1536%2C%22path%22%3A%22.%2Fpackages%2Fgraphql-anywhere%2Flib%2Findex.min.js%22%2C%22size%22%3A1380%7D%5D%2C%22repo%22%3A%22apollographql%2Fapollo-client%22%2C%22branch%22%3A%22package-split%22%2C%22commit_message%22%3A%22Merge%2045001ae74476b4c192f7e68ec94512f578c50bd5%20into%205acacbe672a1dda75b999d6b58cda993e)

I'd be happy to PR a change to encode it differently if desired

**Comment by siddharthkp** [comment]
Related: https://github.com/siddharthkp/bundlesize/pull/86

The url gets truncated by github status api, browsers support super long urls

**Comment by karanjthakkar** [comment]
@jbaxleyiii Can you try out the latest version v0.14.1 to see if this is fixed for you?
