### ISSUE TITLE
Remove the sourcemap comment from the size computation?

### ISSUE THREAD

**Issue by tunnckoCore** [siddharthkp/bundlesize#97]
Currently it counts the sourcemap comment (if there is such) too.
These comments usually are around 20-40 bytes.

**Comment by siddharthkp** [comment]
If your bundle has the comments, they will get shipped to the user, bundlesize counts that.
(bundlesize doesn't build for you)

**Comment by charlike** [comment]
Actually, I'm agree, but probably through option may be more acceptable.

**Comment by siddharthkp** [comment]
Sorry, I don't understand the benefit.

You will ship it to your users, right? So, you should also count it?

**Comment by charlike** [comment]
Benefit is while testing/developing to see the diffs. Moreover, some may not need them or dont care about them.

**Comment by nitin42** [comment]
sourcemap comments are enabled by the implementors and 👇 

> (bundlesize doesn't build for you)

So I agree with @siddharthkp that there are no benefits.

**Comment by siddharthkp** [comment]
Cool, closing this issue.

sorry @charlike!

**Comment by developit** [comment]
I know this is a closed issue, but would you be open to adding an **option** to strip sourcemap comments prior to computing size @siddharthkp?  I prefer to exclude them from size calculations because bundlers strip them when combining modules.

**Comment by reznord** [comment]
I'd prefer going with a flag in this case (if this can be a viable option).

**Comment by siddharthkp** [comment]
@developit @reznord You'll have to educate me a little 😅

Do you ship sourcemap comments to your users? If yes, then it should be counted here.

> I prefer to exclude them from size calculations because bundlers strip them when combining modules

Are you saying that you ship them for the consumers of the lib (applications), but it eventually gets stripped out in the application's build process?

**Comment by siddharthkp** [comment]
Even in the application's case, is it safe to assume that it will always be stripped out? As bundlesize doesn't build the bundles for you, I'm a little touchy about it

**Comment by palashmon** [comment]
Closing this issue for now because it has not had recent activity. Thank you for your contributions.
